### ISSUE TITLE
Differences with VIRK

### ISSUE THREAD

**Issue by thobianchi** [sassoftware/viya-ark#1]
Which are the differences with [VIRK](https://github.com/sassoftware/virk) repo?
Which one should I use, for instance, to start and stop services in a multi machines deployment?

**Comment by jefurbee** [comment]
Hi @thobianchi, 
Thanks for your inquiry. The virk repo has been renamed viya-ark. The former will be sunset/archived in the future, and all new work is being posted to the latter. Please use viya-ark now and moving forward.
