### ISSUE TITLE
viya-deployment-report

### ISSUE THREAD

**Issue by kurthaemmerle** [sassoftware/viya-ark#11]
I got this Error while running “viya-deployment-report” from viya-ark at customer site:

ansible-playbook run-deployment-report.yml -i /opt/sas/sasinstall/sas_viya_playbook/inventory.ini -e "include_package_files=true"

<localhost> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1559895102.52-976022916633/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1559895102.52-976022916633/AnsiballZ_process_sas_host_details.py", line 114, in <module>
    _ansiballz_main()
  File "/root/.ansible/tmp/ansible-tmp-1559895102.52-976022916633/AnsiballZ_process_sas_host_details.py", line 106, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/root/.ansible/tmp/ansible-tmp-1559895102.52-976022916633/AnsiballZ_process_sas_host_details.py", line 49, in invoke_module
    imp.load_module('__main__', mod, module, MOD_DESC)
  File "/tmp/ansible_process_sas_host_details_payload_zvnWIn/__main__.py", line 127, in <module>
  File "/tmp/ansible_process_sas_host_details_payload_zvnWIn/__main__.py", line 90, in main
KeyError: 'results'

fatal: [ViyaNode]: FAILED! => {
    "changed": false, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1559895102.52-976022916633/AnsiballZ_process_sas_host_details.py\", line 114, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1559895102.52-976022916633/AnsiballZ_process_sas_host_details.py\", line 106, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1559895102.52-976022916633/AnsiballZ_process_sas_host_details.py\", line 49, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/tmp/ansible_process_sas_host_details_payload_zvnWIn/__main__.py\", line 127, in <module>\n  File \"/tmp/ansible_process_sas_host_details_payload_zvnWIn/__main__.py\", line 90, in main\nKeyError: 'results'\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", 
    "rc": 1
}

NO MORE HOSTS LEFT ************************************************************************************************************************************************************************************************************************************************************

PLAY RECAP ********************************************************************************************************************************************************************************************************************************************************************
ViyaNode                   : ok=3    changed=0    unreachable=0    failed=1    skipped=2    rescued=0    ignored=0   

Could some one assist here?

**Comment by kevinlinglesas** [comment]
@kurthaemmerle this issue has been fixed and will be in the next release.

**Comment by kevinlinglesas** [comment]
This issue has been addressed by [Viya34-ark-1.5 release](https://sas.service-now.com/nav_to.do?uri=%2Fsc_req_item.do%3Fsys_id%3D121964efdbee7b009b71753a8c9619ae).
