### ISSUE TITLE
PROD Egypt ABE bank, AML8.2 Viya3.5 HA. Urgent support needed, there is regional escalation

### ISSUE THREAD

**Issue by Elsayedhassanin** [sassoftware/viya-ark#110]
**Environment**
- [ ] Ansible version: **2.9**
- [ ] Python version: **3.6**
- [ ] OS version:  **RHEL 8.7 because later not supported with AML8.2**
- [ ] Failed playbook tasks log (or entire playbook log) [Attach]
- [ ] What version of Viya 3.x is being deployed? **viya 3.5**

Dear Team, 
happy new year, 

Our customer ABE has AML8.2 sitting on Viya3.5 with HA Arch over 16 servers, and we are in the Go-live phase. They installed Trend Micro on all servers, and suddenly, we discovered all servers under high load. 

After contacting SAS TS, they provided all extensions and folders that needed to be excluded after this load became normal.

trend micro shared sheet for almost 1500 hits daily over servers from Python, and when we contacted again, SAS TS mentioned only Viya ARK that use Python, so please come back here for support.

to solve the issue, we asked ABE team to exclude what came on sheet; they mentioned, **NO** we need processes or extensions only
[10.33.135.12App_Control_Events_231228.csv](https://github.com/sassoftware/viya-ark/files/13818502/10.33.135.12App_Control_Events_231228.csv)
 

Please find a sample from trendmicro logs for Python hits. We need to know how we can solve this with the customer. Also, one of the points that makes customer push for this is that when they do a full Viya restart, it takes 2 hours, and web nodes reach 300% CPU because trendmicro register python hits compared to before python service took 35 minutes to start.

**Comment by erharb** [comment]
Since this appears to be an environmental issue unrelated to Viya ARK, please open a ticket with SAS Technical Support. The Viya ARK is considered to be optional software that may not cover all scenarios and it seems like your unique environment may need more attention.
