### ISSUE TITLE
Release link missing

### ISSUE THREAD

**Issue by devopsasadm** [sassoftware/viya-ark#12]
This section of the description missing a correct link to the page and errors out with a 404 error

The master branch supports the latest release of SAS Viya.   Visit the releases page for specific information about SAS Viya-ARK and related SAS Viya product releases.

page link: https://github.com/sassoftware/viya-ark/blob/master/releases

**Comment by kevinlinglesas** [comment]
@devopsasadm we are aware of this issue and it has been fixed and will be available in the next release.

**Comment by kevinlinglesas** [comment]
This issue has been addressed by [Viya34-ark-1.5 release](https://sas.service-now.com/nav_to.do?uri=%2Fsc_req_item.do%3Fsys_id%3D121964efdbee7b009b71753a8c9619ae).
