### ISSUE TITLE
Error when running playbook "viya-deployment-report.yml"

### ISSUE THREAD

**Issue by kakitafa** [sassoftware/viya-ark#120]
Getting following error in task "Get SAS host details". See attached for full ansible output

fatal: [deployTarget]: FAILED! => {"changed": false, "module_stderr": "\nTraceback (most recent call last):\n  File \"/tmp/.la_kach02.ansible/ansible-tmp-1725954662.5381758-209137-164362983424090/AnsiballZ_get_sas_host_details.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/tmp/.la_kach02.ansible/ansible-tmp-1725954662.5381758-209137-164362983424090/AnsiballZ_get_sas_host_details.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/tmp/.la_kach02.ansible/ansible-tmp-1725954662.5381758-209137-164362983424090/AnsiballZ_get_sas_host_details.py\", line 48, in invoke_module\n    run_name='__main__', alter_sys=True)\n  File \"/usr/lib64/python3.6/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.6/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/usr/lib64/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_get_sas_host_details_payload_a3ronwig/ansible_get_sas_host_details_payload.zip/ansible/modules/get_sas_host_details.py\", line 1868, in <module>\n  File \"/tmp/ansible_get_sas_host_details_payload_a3ronwig/ansible_get_sas_host_details_payload.zip/ansible/modules/get_sas_host_details.py\", line 1041, in main\n  File \"/tmp/ansible_get_sas_host_details_payload_a3ronwig/ansible_get_sas_host_details_payload.zip/ansible/modules/get_sas_host_details.py\", line 1280, in _get_sas_root_info\nValueError: could not convert string to float: \n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

Ansible version:  2.14.0
python version:  3.9.19
OS version:  Redhat 8.5
SAS viya 3.5 is deployed
[ansible_output.txt](https://github.com/user-attachments/files/16941431/ansible_output.txt)

Able to run other other playbooks such as "viya-services-status.yml" without any issues.

**Comment by erharb** [comment]
The implicated [line 1280 in get_sas_host_details.py](https://github.com/sassoftware/viya-ark/blob/7f2a58f29ba836c828122065037070655c205ec9/playbooks/deployment-report/library/get_sas_host_details.py#L1280) is using output from some OS commands to determine disk space. This same error has recently been experienced only on one other occasion where there were issues with the filesystem and error messages pointing to those issues in the outputs of the commands.

@kakitafa can you try running the following commands on the "deployTarget" host and address any paths with errors seen in the output of the command.

```bash
sudo du --summarize /opt/sas

sudo df -P --print-type /opt/sas
```

**Comment by kakitafa** [comment]
Hi Eric,

See output below from commands.

***@***.*** ~]$ sudo du --summarize /opt/sas
[sudo] password for la_kach02:
du: cannot read directory '/opt/sas/lagring/Lev1': Permission denied
du: cannot read directory '/opt/sas/depot': Permission denied
37616644        /opt/sas
***@***.*** ~]$ sudo df -P --print-type /opt/sas
Filesystem                 Type 1024-blocks     Used Available Capacity Mounted on
/dev/mapper/sas_vg-sas_opt xfs    314419200 38434064 275985136      13% /opt/sas
***@***.*** ~]$

Ps. We are running viya on a single machine.

Kind regards,
Ka-kit Chung
____________________________
Plattformspecialist
Afa Försäkring

Från: Eric Harbeston ***@***.***>
Skickat: den 10 september 2024 16:28
Till: sassoftware/viya-ark ***@***.***>
Kopia: Ka-kit Chung ***@***.***>; Mention ***@***.***>
Ämne: Re: [sassoftware/viya-ark] Error when running playbook "viya-deployment-report.yml" (Issue #120)


Du får inte e-post ofta från ***@***.*** Se varför det här är viktigt.<https://aka.ms/LearnAboutSenderIdentification>


The implicated line 1280 in get_sas_host_details.py<https://github.com/sassoftware/viya-ark/blob/7f2a58f29ba836c828122065037070655c205ec9/playbooks/deployment-report/library/get_sas_host_details.py#L1280> is using output from some OS commands to determine disk space. This same error has recently been experienced only on one other occasion where there were issues with the filesystem and error messages pointing to those issues in the outputs of the commands.

@kakitafa<https://github.com/kakitafa> can you try running the following commands on the "deployTarget" host and address any paths with errors seen in the output of the command.

sudo du --summarize /opt/sas



sudo df -P --print-type /opt/sas

**Comment by erharb** [comment]
@kakitafa you will need to resolve the issues on your file system at the indicated paths `/opt/sas/depot` and `/opt/sas/lagring/Lev1` and then you will be able to successfully run the deployment report. Most likely they are volume or network mount issues. Either delete them or recreate them until you are able to run the `du` command without those errors showing.
