### ISSUE TITLE
unable to install jq with pre-install-playbook

### ISSUE THREAD

**Issue by alan-demarq** [sassoftware/viya-ark#13]
task in 
`https://github.com/sassoftware/viya-ark/blob/master/playbooks/pre-install-playbook/roles/viya-ark.preinstall/tasks/pre.required_packages_config.yml`

 installs JQ using `get_url` method from 

`jq_url: "https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64"`

Error:

> `TASK [viya-ark.preinstall : If jq is not found in /usr/bin, download jq-1.5 utility into it] ************************************************************************************************
fatal: [mas1]: FAILED! => {"changed": false, "msg": "Failed to connect to github.com at port 443: [Errno 110] Connection timed out"}`

Can it be installed using `yum` instead as I know this works without having to alter proxy rules.

Using version: `## Viya34-ark-1.4 - June 5, 2019`

Have used `--skip-tags=jq` to circumvent for the moment - is `JQ` pre-req now?

**Comment by kevinlinglesas** [comment]
@alan-demarq, `jq-1.5` is a requirement for VI and Multi-tenancy and as such has been included in the pre-install playbook.   

If available to the customer, it is acceptable for `jq-1.5` packages to be installed using `yum`.  However, the [Operating System Requirements section](https://go.documentation.sas.com/?docsetId=dplyml0phy0lax&docsetTarget=n0zjykknqs5ln6n1292uvye8ucrb.htm&docsetVersion=3.4&locale=en#p1t4cy4gcuoviln1el9qk8fn22pb) of the SAS Viya 3.4 Linux Deployment Guide stipulates that SAS recommends the `jq-1.5` package be obtained from GitHub.   The implementation of the pre-install playbook follows this recommendation.
