### ISSUE TITLE
restart playbook leaves rabbit  sessions running

### ISSUE THREAD

**Issue by devopsasadm** [sassoftware/viya-ark#14]
i'm having some issues with the restart not giving enough time for the rabbitmq sessions to die.  Is there anything that can be done regarding this?

**Comment by kevinlinglesas** [comment]
I presume you are referring to Mult-Machine Services Utility's viya-services-restart playbook?   Can you provide more details of your failure scenario, please?     How long do rabbitmq sessions typically need to die?

**Comment by cuddlehub** [comment]
Instead of running viya-services-restart.yml:
Try to run the playbook in the following order::
    1. viya-services-stop.yml
    2. viya-services-status.yml
    Note: Make sure viya-services-status.yml has clean run.
    If there is any process left behind,  follow the Tips in the readme to clean the dangling processes.
    https://github.com/sassoftware/viya-ark/blob/master/playbooks/viya-mmsu/README.md
   (re-run) step2 when needed to ensure seeing "No Viya process running" across all machines
   3. viya-services-start.yml

**Comment by devopsasadm** [comment]
I've been using the stop playbook and running a 'ps-ef | grep sas' after it completes on the server with RabbitMQ on it to identify the leftover processes.   Re-running the playbook has not necessarily cleaned them up.   I was looking for a way to have a check in place to make sure everything stopped.  I don't see the same ones today that I saw yesterday and the day before that had the sasrab+ even after trying several stops.

**Comment by cuddlehub** [comment]
Good. Thanks to let us know. Hope it was just a glitch.

After running viya-services-stop.yml, you'll get "Consul is down" message when run playbook viya-services-status.yml

If you just want to re-check any leftover processes after stop, you can re-run stop with --check:
  ansible-playbook viya-ark/playbooks/viya-mmsu/viya-services-stop.yml  --check
and in the log you should see "No Viya process running" if no process was found.
With --check, you can identify those leftover processes first if any. And then decide if they should be cleaned up by passing the enable variable to the playbook:
  ansible-playbook viya-ark/playbooks/viya-mmsu/viya-services-stop.yml -e "enable_stray_cleanup=true"

**Comment by devopsasadm** [comment]
No.  Haven’t had this issue in a while

**Comment by kevinlinglesas** [comment]
Not reported to be occurring now.
