### ISSUE TITLE
Pre-install playbook errors out when ansible is version 2.8

### ISSUE THREAD

**Issue by Carus11** [sassoftware/viya-ark#17]
The pre-install playbook throws an error when ansible is version 2.8 and says the max version needs to be 2.7

at https://support.sas.com/en/documentation/third-party-software-reference/viya/34/support-for-operating-systems.html#ansible

> Ansible
> SAS requires Ansible version 2.5.x through 2.8.x.

**Comment by kevinlinglesas** [comment]
Viya ARK will be updated very soon to correspond with latest release of SAS Viya 3.4 where support for Ansible 2.8 is available.

**Comment by kevinlinglesas** [comment]
[Viya34-ark-1.7](https://github.com/sassoftware/viya-ark/releases/tag/Viya34-ark-1.7) is now available with Ansible 2.8 support.
