### ISSUE TITLE
issue running viyaldpavalidator.yml

### ISSUE THREAD

**Issue by esshab** [sassoftware/viya-ark#19]
the sample file for AD has a couple of missing items. after fixing those i get this error

fatal: [myhost]: FAILED! => {"msg": "The conditional check 'sitedefault.config.application['sas.identities']['administrator'] is defined' failed. The error was: error while evaluating conditional (sitedefault.config.application['sas.identities']['administrator'] is defined): 'dict object' has no attribute 'sas.identities'"}

**Comment by kevinlinglesas** [comment]
Hi @esshab.   We are looking into this.   Can you provide the exact changes you made to the sample file?

**Comment by kevinlinglesas** [comment]
Until a fix can be made, please ensure sitedefault yml file that is being used has:
`sas.identities:
                administrator:'your_user_id'
`

**Comment by kevinlinglesas** [comment]
Release [Viya35-ark-1.0](https://github.com/sassoftware/viya-ark/releases/tag/Viya35-ark-1.0) contains a fix for this issue.   
_**DEPENB-2110 - LDAP Validator update sitedefault_sample_ad.ym to be consistent with sitedefault_sample_openldap.yml**_
