### ISSUE TITLE
virk anonymous bind

### ISSUE THREAD

**Issue by devopsasadm** [sassoftware/viya-ark#20]
Hi,

Can you add the "#anonymousBind: false" to the sitedefault_sample_ad.yml and add notes about it about where to change this for convenience in the sitedefault.yml file?   I'm was getting errors on this when running a check against AD that does not allow anonymousBind and the viyaldapvalidator.yml checks it to see if anonymousbinding is allowed by default. 

Thanks in advance!

**Comment by kevinlinglesas** [comment]
Sorry for the delayed response to this issue.  This will be addressed in an future release of Viya ARK.

**Comment by AlissaSchleich** [comment]
This suggestion has moved to our queue
