### ISSUE TITLE
Failed to connect to the host via SSH

### ISSUE THREAD

**Issue by mathur1234** [sassoftware/viya-ark#24]
Hi,

I am running into "Failed to connect to the host via SSH: Shared Connection to the host is closed" issues while bringing up the services through SAS Viya ARK playbook. The playbook is viya-services-start.yml file. 

I am able to bring up the services with SAS VIYA ARK playbook in lower environments without any issues. 

The one difference in this environment is the home directory for sas account, it is not the default /home/sas. I created new SSH keys, stopped all the services and tried but with every attempt it fails at the same step with same error.

The step it fails is while brining up the WebServer. See the attached screenshot for more details.

![SAS Viya SSH error](https://user-images.githubusercontent.com/57728267/68798940-52be9600-0625-11ea-9ade-996ccfc17e13.JPG)

**Comment by kevinlinglesas** [comment]
@erharb, can you and @cuddlehub take a look at this issue please?

**Comment by erharb** [comment]
@mathur1234 that appears to be a general ansible message indicating something either in the inventory file or environment itself is not setup properly, since the viya-ark doesn't do any of its own ssh connections outside of what ansible itself does.

To verify your connection with ansible try running this command until you get it working:
`ansible deployTarget -m shell -a "hostname -f"`

**Comment by erwangranger** [comment]
Hello @mathur1234 , 

I wonder if this might be due to the SSH ClientAlive Interval setting. 
Could you possibly also run the following command to gather that value from all the hosts: 

```
ansible all -b -m shell -a " sshd -T | grep -i ClientAliveInterval "
```

If that command works and returns a result, can you post it here?

**Comment by mathur1234** [comment]
> @mathur1234 that appears to be a general ansible message indicating something either in the inventory file or environment itself is not setup properly, since the viya-ark doesn't do any of its own ssh connections outside of what ansible itself does.
> To verify your connection with ansible try running this command until you get it working:
> ansible deployTarget -m shell -a "hostname -f"
@erharb - see the attached image - no issues with ansible connections.

**Comment by mathur1234** [comment]
@erwangranger - See the attached image. 
![ClientLiveInterval](https://user-images.githubusercontent.com/57728267/68900552-14e36f80-0702-11ea-933a-d4d2173f0e07.JPG)

**Comment by mathur1234** [comment]
This is the snippet from the Dev environment for both the Ansible connection verification and ClientAliveInerval.

![Dev](https://user-images.githubusercontent.com/57728267/68901542-1c0b7d00-0704-11ea-949a-9dea501ccb12.JPG)

**Comment by erwangranger** [comment]
I can't really imagine why it would work better in dev with 180 than in prod with 600, so there might be more at play than just the clientaliveinterval. 
In the case I've heard of, changing that value from 900 to 3600 helped with those long running tasks. 

However, it does seem like it only fails on tasks that take a really long time to complete. Right?
In a case that was similar to yours, the following command helped determine the problem: 

```bash
ansible all -m shell -a "sleep 30000" -vvvv
```

This command should sleep for a really long time. If you have timeouts, it should fail after a certain amount of time, giving you an idea on what your effective timeout is. At that point, you should be able to update those ssh timeout settings to ensure the ssh connection stays alive longer. 
I hope this helps.

**Comment by mathur1234** [comment]
@erwangranger 

See the attached screenshot for the details. The output from timeout test - it fails at the webserver, worker 5 and 5 with a same "Failed to connect to the host" error. The test is still running in Dev and PROD environments. 

![image](https://user-images.githubusercontent.com/57728267/68963175-57f61f00-07a4-11ea-8af1-7eff56d7ecfa.png)

**Comment by erwangranger** [comment]
Thanks @mathur1234 , that does confirm a problem with your SSH timing out. 
I can't guess exactly what needs to be updated in your environment. 

If I were you, I'd run `sudo sshd -T` on a server that has the problem and then on a server that does not have the problem. Then I'd compare the SSH settings to try to figure out which one(s) need to be updated.

**Comment by mathur1234** [comment]
Thanks @erwangranger - I see couple of variables have different values. Please have a look at the image and let me know which ones do you think are the key contributor to the ssh timing out issues.

![image](https://user-images.githubusercontent.com/57728267/69079005-1b762d80-0a07-11ea-9129-aea369b84811.png)

**Comment by cuddlehub** [comment]
ClientAliveInterval 600
ClientAliveCountMax 0
For IVVV, after 600 seconds, the ssh session will be terminated, with no keep alive package even being sent. If possible, comment the above values which will use the default value (as following), then try to rerun the playbook.
#ClientAliveInterval 0
#ClientAliveCountMax 3

If still seeing the same issue, please issue the following command and send us the output:
ansible all -m ping -vvvvv > /tmp/ping.out         #with 5 v's

**Comment by mathur1234** [comment]
@cuddlehub - If that is the case then wouldn't we run into timing out issues in Dev environment since Dev has 180 seconds clientliveinterval set?

**Comment by cuddlehub** [comment]
A ref. link from google search: 
http://fibrevillage.com/sysadmin/172-how-to-keep-idle-ssh-connection-alive
You might need to modify the parameters to fit to your environment.
