### ISSUE TITLE
Viya 3.4 Service Start Issue using viya-ark

### ISSUE THREAD

**Issue by SaikatKumarMandal** [sassoftware/viya-ark#25]
Hi Team,
while i am running “ansible-playbook viya-ark-master/playbooks/viya-mmsu/viya-services-start.yml" i got one failed status for CAS controler and each workers node. But “/etc/init.d/sas-viya-all-services status” showing everything “up”.  

fatal: [cas-worker-4]: FAILED! => {"attempts": 2, "changed": true, "cmd": "/etc/init.d/sas-viya-all-services start", "delta": "0:01:40.570858", "end": "2019-11-18 16:35:24.158579", "rc": 0, "start": "2019-11-18 16:33:43.587721", "stderr": "", "stderr_lines": [], "stdout": "sas-viya-consul-default is already started\nsas-viya-alert-track-default is already started\nsas-viya-ops-agent-default is already started\nsas-viya-watch-log-default is already started\nStarting sas-viya-sasgpud-default\nThere are still 1 services starting.  Waiting for them to be ready - Sleeping...\nThere are still 1 services starting.  Waiting for them to be ready - Sleeping...\nThere are still 1 services starting.  Waiting for them to be ready - Sleeping...\nThere are still 1 services starting.  Waiting for them to be ready - Sleeping...\nThere are still 1 services starting.  Waiting for them to be ready - Sleeping...\nWARNING: sas-viya-sasgpud-default has been started and died 4 times.  It will not be restarted.\n         Other services may fail to start due to this.  Check logs, remedy the problem and try again.\n\nService start time summary: \n                                              SERVICE ELAPSED (+/-10)\n   sas-viya-sasgpud-default                                Failed!\n\nsas-services completed in 00:01:41", "stdout_lines": ["sas-viya-consul-default is already started", "sas-viya-alert-track-default is already started", "sas-viya-ops-agent-default is already started", "sas-viya-watch-log-default is already started", "Starting sas-viya-sasgpud-default", "There are still 1 services starting.  Waiting for them to be ready - Sleeping...", "There are still 1 services starting.  Waiting for them to be ready - Sleeping...", "There are still 1 services starting.  Waiting for them to be ready - Sleeping...", "There are still 1 services starting.  Waiting for them to be ready - Sleeping...", "There are still 1 services starting.  Waiting for them to be ready - Sleeping...", "WARNING: sas-viya-sasgpud-default has been started and died 4 times.  It will not be restarted.", "         Other services may fail to start due to this.  Check logs, remedy the problem and try again.", "", "Service start time summary: ", "                                              SERVICE ELAPSED (+/-10)", "   sas-viya-sasgpud-default                                Failed!", "", "sas-services completed in 00:01:41"]}

**Comment by erharb** [comment]
The sasgpud service is supposed to only be enabled automatically if a GPU is present, otherwise it is supposed to be added to the `svc-ignore` file so sas-viya-all-services won't attempt to start it.

For example, does yours look something like this?
```
$ cat /opt/sas/viya/config/etc/viya-svc-mgr/svc-ignore

# Place the name of init scripts that sas-viya-all-services should not
# control in this file.  lines that start with # are comments
# and will be ignored.
# sas-viya-casworker-default
sas-viya-sasgpud-default
```

**Comment by SaikatKumarMandal** [comment]
@erharb : Thank you for your input.
Yes, output looks same. not sure why it was trying to start . when i looked viya-services-status.yml output ; "sas-viya-sasgpud-default" service was showing "down" in CAS controler and all works. I had to run /opt/sas/viya/home/bin/sasgpud_setup to disable  SAS GPU Reservation Service and now  "viya-services-start.yml" working fine.
