### ISSUE TITLE
Error running VIYA 3.5 - SAS Viya Deployment Report Playbook

### ISSUE THREAD

**Issue by LucaOSAS** [sassoftware/viya-ark#29]
hi
I tried several times to execute the playbook ( 
ansible-playbook viya-ark/playbooks/deployment-report/viya-deployment-report.yml ) but without success, here is the error:

PLAY [Viya Deployment Report] ************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] *******************************************************************************************************************************************************************************************************************
ok: [deployTarget]
ok: [casworker-3]
ok: [casworker-1]
ok: [casworker-2]

TASK [Check for existing data - ()] ******************************************************************************************************************************************************************************************************
skipping: [deployTarget]

TASK [Load existing data file] ***********************************************************************************************************************************************************************************************************
skipping: [deployTarget]

TASK [Get SAS host details] **************************************************************************************************************************************************************************************************************
fatal: [casworker-3]: FAILED! => {"changed": false, "command_stderr": null, "msg": "Command df -P --print-type failed."}
fatal: [casworker-1]: FAILED! => {"changed": false, "command_stderr": null, "msg": "Command df -P --print-type failed."}
fatal: [casworker-2]: FAILED! => {"changed": false, "command_stderr": null, "msg": "Command df -P --print-type failed."}
ok: [deployTarget]

TASK [Process SAS host details] **********************************************************************************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: KeyError: 'rc'
fatal: [deployTarget -> localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/.root.ansible/ansible-tmp-1575308039.17-199550580084771/AnsiballZ_process_sas_host_details.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/tmp/.root.ansible/ansible-tmp-1575308039.17-199550580084771/AnsiballZ_process_sas_host_details.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/tmp/.root.ansible/ansible-tmp-1575308039.17-199550580084771/AnsiballZ_process_sas_host_details.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible.modules.process_sas_host_details', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib64/python2.7/runpy.py\", line 176, in run_module\n    fname, loader, pkg_name)\n  File \"/usr/lib64/python2.7/runpy.py\", line 82, in _run_module_code\n    mod_name, mod_fname, mod_loader, pkg_name)\n  File \"/usr/lib64/python2.7/runpy.py\", line 72, in _run_code\n    exec code in run_globals\n  File \"/tmp/ansible_process_sas_host_details_payload_nliAmF/ansible_process_sas_host_details_payload.zip/ansible/modules/process_sas_host_details.py\", line 616, in <module>\n  File \"/tmp/ansible_process_sas_host_details_payload_nliAmF/ansible_process_sas_host_details_payload.zip/ansible/modules/process_sas_host_details.py\", line 233, in main\nKeyError: 'rc'\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

NO MORE HOSTS LEFT ***********************************************************************************************************************************************************************************************************************

PLAY RECAP *******************************************************************************************************************************************************************************************************************************
casworker-1                : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
casworker-2                : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
casworker-3                : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
deployTarget               : ok=2    changed=0    unreachable=0    failed=1    skipped=2    rescued=0    ignored=0
localhost                  : ok=1    changed=0    unreachable=0    failed=0    skipped=1    rescued=0    ignored=0

Ansible version: 
ansible 2.9.1
  config file = /sas/install/sas_viya_playbook/ansible.cfg
  configured module search path = [u'/sas/install/sas_viya_playbook/library']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Aug  7 2019, 00:51:29) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]

thanks
Luca

**Comment by erharb** [comment]
@LucaOSAS we discovered this in testing late in the cycle (SAS rndjira ticket VIYAARK-60), apparently the `df` command return code is non-zero if you have any networked mount points that are experiencing errors. For example:

```
ddtlaxvm18.unx.sas.com> df
df: ‘/r/cardio/vol/luns’: Stale file handle
Filesystem                                             1K-blocks         Used   Available Use% Mounted on
/dev/mapper/vg_default-lv_root                         124231140     42799276    76005252  37% /
devtmpfs                                                65916136            0    65916136   0% /dev
```

You will either need to address your mount issue or skip running the deployment report tag as indicated.

The fix is already merged internally for a January release, which involves adding additional error protection to the deployment report for issues that can arise with df or du commands.

**Comment by LucaOSAS** [comment]
hi Eric
but seems that this playbook does not have tags:
  play #2 (sas_all): Viya Deployment Report     TAGS: []
    tasks:
      Check for existing data - ({{ existing_data_file }})      TAGS: []
      Load existing data file   TAGS: []
      Get SAS host details      TAGS: []
      Process SAS host details  TAGS: []
      set_fact  TAGS: []
      set_fact  TAGS: []
      Create Viya Deployment Report data file   TAGS: []
      Viya Deployment Report Data location      TAGS: []
      Create Viya Deployment HTML Report        TAGS: []
      Viya Deployment Report location   TAGS: []

how I can fix this?
thanks
Luca

**Comment by erharb** [comment]
the readme in the viya-upgrade folder shows all applicable tags:

https://github.com/sassoftware/viya-ark/blob/master/playbooks/viya-upgrade/README.md#pre-upgrade-task-details

**Comment by LucaOSAS** [comment]
Eric
Sorry but I’m executing the deployment report playbook’s and not the pre-upgrade, so I cannot use the skip tags because there isn’t tags defined

Or I’m wrong something?

Thanks
Luca


Da: Eric Harbeston <notifications@github.com>
Inviato: lunedì 2 dicembre 2019 18:20
A: sassoftware/viya-ark <viya-ark@noreply.github.com>
Cc: Luca Oliosi <Luca.Oliosi@sas.com>; Mention <mention@noreply.github.com>
Oggetto: Re: [sassoftware/viya-ark] Error running VIYA 3.5 - SAS Viya Deployment Report Playbook (#29)


EXTERNAL

the readme in the viya-upgrade folder shows all applicable tags:

https://github.com/sassoftware/viya-ark/blob/master/playbooks/viya-upgrade/README.md#pre-upgrade-task-details<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fsassoftware%2Fviya-ark%2Fblob%2Fmaster%2Fplaybooks%2Fviya-upgrade%2FREADME.md%23pre-upgrade-task-details&data=02%7C01%7Cluca.oliosi%40sas.com%7Cb9526d50675748faa12408d7774bd1bf%7Cb1c14d5c362545b3a4309552373a0c2f%7C0%7C0%7C637109039835135187&sdata=1nQCLq%2B6DP6LnbmMr3oypCDYJcI80T%2FD1QWKGRvqjEQ%3D&reserved=0>

**Comment by erharb** [comment]
My apologies Luca, I misread that it failed running the deployment report within pre-upgrade, but you're running deployment report directly. This means you'll need to address your network mount issues first before you can successfully get a deployment report.

**Comment by LucaOSAS** [comment]
Thank you
Luca

Da: Eric Harbeston <notifications@github.com>
Inviato: lunedì 2 dicembre 2019 18:45
A: sassoftware/viya-ark <viya-ark@noreply.github.com>
Cc: Luca Oliosi <Luca.Oliosi@sas.com>; Mention <mention@noreply.github.com>
Oggetto: Re: [sassoftware/viya-ark] Error running VIYA 3.5 - SAS Viya Deployment Report Playbook (#29)


EXTERNAL

My apologies Luca, I misread that it failed running the deployment report within pre-upgrade, but you're running deployment report directly. This means you'll need to address your network mount issues first before you can successfully get a deployment report.
