### ISSUE TITLE
suid on mount points

### ISSUE THREAD

**Issue by henriquevaskys** [sassoftware/viya-ark#30]
Hi

Suggestion of something I hit recently: could you add a check into the mount points for /opt/sas if it is mounted with suid (or, not mounted with nosuid)?

I think the best way is to look for /etc/fstab or mount command and check if suid/nosuid is used.

Thanks
Henri

**Comment by AlissaSchleich** [comment]
Thank you for your suggestion.   It has been added to our list of features to consider for future releases.
We will post back when the suggestion is implemented.
