### ISSUE TITLE
The task performance_config in pre-install is not working correctly.

### ISSUE THREAD

**Issue by scnljj** [sassoftware/viya-ark#31]
The facts "kernel_XXX" are set with string value:
 kernel_SEMMSL: "{{ kernel_sem.stdout.split()[0] }}"

But later they are used to be compared with integer value:
item.value > kernel_XXXX

This conditional result is always "false".
So the performance configurations will never be changed.

**Comment by kevinlinglesas** [comment]
@scnljj can you provide some information on the version of Ansible and Python being used when you see this issue?  Can you also provide any of the task output with -vvv verbosity?

I believe that this is a known issue that a fix will be forthcoming in the next release of Viya ARK.  The information I ask for above will help us to better determine if it is in fact the known issue.

**Comment by scnljj** [comment]
@kevinlinglesas Sure. Here is the information.

################# Version information #################
# ansible --version
ansible 2.7.2
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Jun 11 2019, 14:33:56) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]

################# Output information **(partial)** #################

PLAYBOOK: viya_pre_install_playbook.yml ****************************************************************************************************************
2 plays in viya_pre_install_playbook.yml

PLAY [localhost] ***************************************************************************************************************************************

TASK [Gathering Facts] *********************************************************************************************************************************
task path: /root/viya-ark/playbooks/common/handle_hostgroup_hyphens.yml:14
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: root
<127.0.0.1> EXEC /bin/sh -c 'echo ~root && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1576113882.18-214692290366582 `" && echo ansible-tmp-1576113882.18-214692290366582="` echo /root/.ansible/tmp/ansible-tmp-1576113882.18-214692290366582 `" ) && sleep 0'
Using module file /usr/lib/python2.7/site-packages/ansible/modules/system/setup.py
<127.0.0.1> PUT /root/.ansible/tmp/ansible-local-25864UX6i2f/tmpqZYX6h TO /root/.ansible/tmp/ansible-tmp-1576113882.18-214692290366582/AnsiballZ_setup.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1576113882.18-214692290366582/ /root/.ansible/tmp/ansible-tmp-1576113882.18-214692290366582/AnsiballZ_setup.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python2 /root/.ansible/tmp/ansible-tmp-1576113882.18-214692290366582/AnsiballZ_setup.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1576113882.18-214692290366582/ > /dev/null 2>&1 && sleep 0'
ok: [localhost]
META: ran handlers

TASK [Determine if groups with hyphens need mapped using underscores] **********************************************************************************
task path: /root/viya-ark/playbooks/common/handle_hostgroup_hyphens.yml:16
skipping: [localhost] => (item={'key': u'ungrouped', 'value': []})  => {
    "changed": false,
    "hyphen_groups": {
        "key": "ungrouped",
        "value": []
    },
    "skip_reason": "Conditional result was False"
}
skipping: [localhost] => (item={'key': u'all', 'value': [u'deployTarget']})  => {
    "changed": false,
    "hyphen_groups": {
        "key": "all",
        "value": [
            "deployTarget"
        ]
    },
    "skip_reason": "Conditional result was False"
}
skipping: [localhost] => (item={'key': u'sas_all', 'value': [u'deployTarget']})  => {
    "changed": false,
    "hyphen_groups": {
        "key": "sas_all",
        "value": [
            "deployTarget"
        ]
    },
    "skip_reason": "Conditional result was False"
}
META: ran handlers
META: ran handlers

PLAY [sas_all] *****************************************************************************************************************************************

TASK [Gathering Facts] *********************************************************************************************************************************
task path: /root/viya-ark/playbooks/pre-install-playbook/viya_pre_install_playbook.yml:48
<deployTarget> ESTABLISH LOCAL CONNECTION FOR USER: root
<deployTarget> EXEC /bin/sh -c 'echo ~root && sleep 0'
<deployTarget> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1576113885.82-155328798164972 `" && echo ansible-tmp-1576113885.82-155328798164972="` echo /root/.ansible/tmp/ansible-tmp-1576113885.82-155328798164972 `" ) && sleep 0'
Using module file /usr/lib/python2.7/site-packages/ansible/modules/system/setup.py
<deployTarget> PUT /root/.ansible/tmp/ansible-local-25864UX6i2f/tmp2FovNK TO /root/.ansible/tmp/ansible-tmp-1576113885.82-155328798164972/AnsiballZ_setup.py
<deployTarget> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1576113885.82-155328798164972/ /root/.ansible/tmp/ansible-tmp-1576113885.82-155328798164972/AnsiballZ_setup.py && sleep 0'
<deployTarget> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1576113885.82-155328798164972/AnsiballZ_setup.py && sleep 0'
<deployTarget> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1576113885.82-155328798164972/ > /dev/null 2>&1 && sleep 0'
ok: [deployTarget]
META: ran handlers

TASK [viya-ark.preinstall : WARNING: If you are running this playbook without the --check parameter, it WILL perform changes to your systems.] *********
task path: /root/viya-ark/playbooks/pre-install-playbook/roles/viya-ark.preinstall/tasks/pre.pause.yml:3
skipping: [deployTarget] => {
    "changed": false,
    "skip_reason": "Conditional result was False"
}

TASK [viya-ark.preinstall : Query current value of kernel.sem] *****************************************************************************************
task path: /root/viya-ark/playbooks/pre-install-playbook/roles/viya-ark.preinstall/tasks/pre.performance_config.yml:8
<deployTarget> ESTABLISH LOCAL CONNECTION FOR USER: root
<deployTarget> EXEC /bin/sh -c 'echo ~root && sleep 0'
<deployTarget> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1576113888.75-59141189034968 `" && echo ansible-tmp-1576113888.75-59141189034968="` echo /root/.ansible/tmp/ansible-tmp-1576113888.75-59141189034968 `" ) && sleep 0'
Using module file /usr/lib/python2.7/site-packages/ansible/modules/commands/command.py
<deployTarget> PUT /root/.ansible/tmp/ansible-local-25864UX6i2f/tmpLsu24k TO /root/.ansible/tmp/ansible-tmp-1576113888.75-59141189034968/AnsiballZ_command.py
<deployTarget> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1576113888.75-59141189034968/ /root/.ansible/tmp/ansible-tmp-1576113888.75-59141189034968/AnsiballZ_command.py && sleep 0'
<deployTarget> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1576113888.75-59141189034968/AnsiballZ_command.py && sleep 0'
<deployTarget> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1576113888.75-59141189034968/ > /dev/null 2>&1 && sleep 0'
changed: [deployTarget] => {
    "changed": true,
    "cmd": "cat /proc/sys/kernel/sem",
    "delta": "0:00:00.161374",
    "end": "2019-12-11 20:24:49.326583",
    "invocation": {
        "module_args": {
            "_raw_params": "cat /proc/sys/kernel/sem",
            "_uses_shell": true,
            "argv": null,
            "chdir": null,
            "creates": null,
            "executable": null,
            "removes": null,
            "stdin": null,
            "warn": true
        }
    },
    "rc": 0,
    "start": "2019-12-11 20:24:49.165209",
    "stderr": "",
    "stderr_lines": [],
    "stdout": "250\t32000\t32\t128",
    "stdout_lines": [
        "250\t32000\t32\t128"
    ]
}

TASK [viya-ark.preinstall : Register current SEMMSL] ***************************************************************************************************
task path: /root/viya-ark/playbooks/pre-install-playbook/roles/viya-ark.preinstall/tasks/pre.performance_config.yml:13
ok: [deployTarget] => {
    "ansible_facts": {
        "kernel_SEMMSL": "250"
    },
    "changed": false
}

TASK [viya-ark.preinstall : Register current SEMMNS] ***************************************************************************************************
task path: /root/viya-ark/playbooks/pre-install-playbook/roles/viya-ark.preinstall/tasks/pre.performance_config.yml:17
ok: [deployTarget] => {
    "ansible_facts": {
        "kernel_SEMMNS": "32000"
    },
    "changed": false
}

TASK [viya-ark.preinstall : Register current SEMOPM] ***************************************************************************************************
task path: /root/viya-ark/playbooks/pre-install-playbook/roles/viya-ark.preinstall/tasks/pre.performance_config.yml:21
ok: [deployTarget] => {
    "ansible_facts": {
        "kernel_SEMOPM": "32"
    },
    "changed": false
}

TASK [viya-ark.preinstall : Register current SEMMNI] ***************************************************************************************************
task path: /root/viya-ark/playbooks/pre-install-playbook/roles/viya-ark.preinstall/tasks/pre.performance_config.yml:25
ok: [deployTarget] => {
    "ansible_facts": {
        "kernel_SEMMNI": "128"
    },
    "changed": false
}

TASK [viya-ark.preinstall : Update SEMMSL if the current system value is lower] ************************************************************************
task path: /root/viya-ark/playbooks/pre-install-playbook/roles/viya-ark.preinstall/tasks/pre.performance_config.yml:30
skipping: [deployTarget] => (item={u'name': u'kernel.sem.SEMMSL', u'value': 512})  => {
    "changed": false,
    "item": {
        "name": "kernel.sem.SEMMSL",
        "value": 512
    },
    "skip_reason": "Conditional result was False"
}
skipping: [deployTarget] => (item={u'name': u'kernel.sem.SEMMNS', u'value': 32000})  => {
    "changed": false,
    "item": {
        "name": "kernel.sem.SEMMNS",
        "value": 32000
    },
    "skip_reason": "Conditional result was False"
}
skipping: [deployTarget] => (item={u'name': u'kernel.sem.SEMOPM', u'value': 256})  => {
    "changed": false,
    "item": {
        "name": "kernel.sem.SEMOPM",
        "value": 256
    },
    "skip_reason": "Conditional result was False"
}
skipping: [deployTarget] => (item={u'name': u'kernel.sem.SEMMNI', u'value': 1024})  => {
    "changed": false,
    "item": {
        "name": "kernel.sem.SEMMNI",
        "value": 1024
    },
    "skip_reason": "Conditional result was False"
}

TASK [viya-ark.preinstall : Update SEMMNS if the current system value is lower] ************************************************************************
task path: /root/viya-ark/playbooks/pre-install-playbook/roles/viya-ark.preinstall/tasks/pre.performance_config.yml:39
skipping: [deployTarget] => (item={u'name': u'kernel.sem.SEMMSL', u'value': 512})  => {
    "changed": false,
    "item": {
        "name": "kernel.sem.SEMMSL",
        "value": 512
    },
    "skip_reason": "Conditional result was False"
}
skipping: [deployTarget] => (item={u'name': u'kernel.sem.SEMMNS', u'value': 32000})  => {
    "changed": false,
    "item": {
        "name": "kernel.sem.SEMMNS",
        "value": 32000
    },
    "skip_reason": "Conditional result was False"
}
skipping: [deployTarget] => (item={u'name': u'kernel.sem.SEMOPM', u'value': 256})  => {
    "changed": false,
    "item": {
        "name": "kernel.sem.SEMOPM",
        "value": 256
    },
    "skip_reason": "Conditional result was False"
}
skipping: [deployTarget] => (item={u'name': u'kernel.sem.SEMMNI', u'value': 1024})  => {
    "changed": false,
    "item": {
        "name": "kernel.sem.SEMMNI",
        "value": 1024
    },
    "skip_reason": "Conditional result was False"
}

TASK [viya-ark.preinstall : Update SEMOPM if the current system value is lower] ************************************************************************
task path: /root/viya-ark/playbooks/pre-install-playbook/roles/viya-ark.preinstall/tasks/pre.performance_config.yml:48
skipping: [deployTarget] => (item={u'name': u'kernel.sem.SEMMSL', u'value': 512})  => {
    "changed": false,
    "item": {
        "name": "kernel.sem.SEMMSL",
        "value": 512
    },
    "skip_reason": "Conditional result was False"
}
skipping: [deployTarget] => (item={u'name': u'kernel.sem.SEMMNS', u'value': 32000})  => {
    "changed": false,
    "item": {
        "name": "kernel.sem.SEMMNS",
        "value": 32000
    },
    "skip_reason": "Conditional result was False"
}
skipping: [deployTarget] => (item={u'name': u'kernel.sem.SEMOPM', u'value': 256})  => {
    "changed": false,
    "item": {
        "name": "kernel.sem.SEMOPM",
        "value": 256
    },
    "skip_reason": "Conditional result was False"
}
skipping: [deployTarget] => (item={u'name': u'kernel.sem.SEMMNI', u'value': 1024})  => {
    "changed": false,
    "item": {
        "name": "kernel.sem.SEMMNI",
        "value": 1024
    },
    "skip_reason": "Conditional result was False"
}

TASK [viya-ark.preinstall : Update SEMMNI if the current system value is lower] ************************************************************************
task path: /root/viya-ark/playbooks/pre-install-playbook/roles/viya-ark.preinstall/tasks/pre.performance_config.yml:58
skipping: [deployTarget] => (item={u'name': u'kernel.sem.SEMMSL', u'value': 512})  => {
    "changed": false,
    "item": {
        "name": "kernel.sem.SEMMSL",
        "value": 512
    },
    "skip_reason": "Conditional result was False"
}
skipping: [deployTarget] => (item={u'name': u'kernel.sem.SEMMNS', u'value': 32000})  => {
    "changed": false,
    "item": {
        "name": "kernel.sem.SEMMNS",
        "value": 32000
    },
    "skip_reason": "Conditional result was False"
}
skipping: [deployTarget] => (item={u'name': u'kernel.sem.SEMOPM', u'value': 256})  => {
    "changed": false,
    "item": {
        "name": "kernel.sem.SEMOPM",
        "value": 256
    },
    "skip_reason": "Conditional result was False"
}
skipping: [deployTarget] => (item={u'name': u'kernel.sem.SEMMNI', u'value': 1024})  => {
    "changed": false,
    "item": {
        "name": "kernel.sem.SEMMNI",
        "value": 1024
    },
    "skip_reason": "Conditional result was False"
}

TASK [viya-ark.preinstall : Generate new kernel semaphore string] **************************************************************************************
task path: /root/viya-ark/playbooks/pre-install-playbook/roles/viya-ark.preinstall/tasks/pre.performance_config.yml:68
ok: [deployTarget] => {
    "ansible_facts": {
        "kernel_semaphore_new": "250\t32000\t32\t128"
    },
    "changed": false
}

TASK [viya-ark.preinstall : Configure systemctl params for kernal semaphores in /etc/sysctl] ***********************************************************
task path: /root/viya-ark/playbooks/pre-install-playbook/roles/viya-ark.preinstall/tasks/pre.performance_config.yml:73
<deployTarget> ESTABLISH LOCAL CONNECTION FOR USER: root
<deployTarget> EXEC /bin/sh -c 'echo ~root && sleep 0'
<deployTarget> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1576113890.29-127658198414736 `" && echo ansible-tmp-1576113890.29-127658198414736="` echo /root/.ansible/tmp/ansible-tmp-1576113890.29-127658198414736 `" ) && sleep 0'
Using module file /usr/lib/python2.7/site-packages/ansible/modules/system/sysctl.py
<deployTarget> PUT /root/.ansible/tmp/ansible-local-25864UX6i2f/tmpUGaXly TO /root/.ansible/tmp/ansible-tmp-1576113890.29-127658198414736/AnsiballZ_sysctl.py
<deployTarget> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1576113890.29-127658198414736/ /root/.ansible/tmp/ansible-tmp-1576113890.29-127658198414736/AnsiballZ_sysctl.py && sleep 0'
<deployTarget> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1576113890.29-127658198414736/AnsiballZ_sysctl.py && sleep 0'
<deployTarget> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1576113890.29-127658198414736/ > /dev/null 2>&1 && sleep 0'
ok: [deployTarget] => {
    "changed": false,
    "invocation": {
        "module_args": {
            "ignoreerrors": false,
            "name": "kernel.sem",
            "reload": true,
            "state": "present",
            "sysctl_file": "/etc/sysctl.conf",
            "sysctl_set": true,
            "value": "250\t32000\t32\t128"
        }
    }
}

**Comment by kevinlinglesas** [comment]
Thank you for the details.   This is the known issue I spoke of above and a fix will be available in the next release of Viya ARK.
