### ISSUE TITLE
Error running viya-ark

### ISSUE THREAD

**Issue by domara11** [sassoftware/viya-ark#33]
[root@alisa1 sas_viya_playbook]# ansible-playbook -vvvv viya-ark/playbooks/viya-mmsu/viya-services-status.yml
ansible-playbook 2.9.1
  config file = /sas/install/sas_viya_playbook/ansible.cfg
  configured module search path = [u'/sas/install/sas_viya_playbook/library']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible-playbook
  python version = 2.7.5 (default, May 31 2018, 09:41:32) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
Using /sas/install/sas_viya_playbook/ansible.cfg as config file
setting up inventory plugins
host_list declined parsing /sas/install/sas_viya_playbook/inventory.ini as it did not pass its verify_file() method
script declined parsing /sas/install/sas_viya_playbook/inventory.ini as it did not pass its verify_file() method
auto declined parsing /sas/install/sas_viya_playbook/inventory.ini as it did not pass its verify_file() method
yaml declined parsing /sas/install/sas_viya_playbook/inventory.ini as it did not pass its verify_file() method
Parsed /sas/install/sas_viya_playbook/inventory.ini inventory source with ini plugin
ERROR! Syntax Error while loading YAML.
  mapping values are not allowed in this context

The error appears to be in '/sas/install/sas_viya_playbook/viya-ark/playbooks/viya-mmsu/viya-services-status.yml': line 119, column 71, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

    <span class="Progress progress-pjax-loader position-fixed width-full js-pjax-loader-bar">
      <span class="progress-pjax-loader-bar top-0 left-0" style="width: 0%;"></span>
                                                                      ^ here
We could be wrong, but this one looks like it might be an issue with
unbalanced quotes. If starting a value with a quote, make sure the
line ends with the same set of quotes. For instance this arbitrary
example:

    foo: "bad" "wolf"

Could be written as:

    foo: '"bad" "wolf"'

**Comment by domara11** [comment]
Ansible versions: 
Single machine deployment - 2.6.1 
Multi machine deployment - 2.8.7
Tested with 2.9.1 - same output as below.
Viya 3.4 , RHEL 7.5

**Comment by erharb** [comment]
@domara11 the [viya-services-status.yml](https://github.com/sassoftware/viya-ark/blob/master/playbooks/viya-mmsu/viya-services-status.yml) file doesn't have html code such as `<span>` tags in it, it sounds like perhaps you downloaded Viya ARK incorrectly. You have two options for obtaining Viya ARK:

- git clone https://github.com/sassoftware/viya-ark.git
- download zip/tar.gz file from [latest release page](https://github.com/sassoftware/viya-ark/releases/latest)

**Comment by domara11** [comment]
Yes, sorry. You can delete my issue. It was file download problem - after cloning whole download - script works fine. Thanks

**Comment by AlissaSchleich** [comment]
Happy to help.
