### ISSUE TITLE
pre-install reports shell tasks as "changed" when no changes were made

### ISSUE THREAD

**Issue by bheinsius** [sassoftware/viya-ark#35]
I ran the playbook from https://github.com/sassoftware/viya-ark/tree/Viya35-ark-1.1 as follows:

```
ansible-playbook viya_pre_install_playbook.yml -i pre-install.inventory.ini --skip-tags skipmemfail,skipipsfail
```

and got this result:

```
deployTarget : ok=137  changed=3    unreachable=0    failed=0    skipped=49   rescued=0    ignored=0
localhost    : ok=1    changed=0    unreachable=0    failed=0    skipped=1    rescued=0    ignored=0
```

When I ran it again it again reported 3 changes.
From the playbook output:

```
TASK [viya-ark.preinstall : Query current value of kernel.sem] 
changed: [deployTarget]

TASK [viya-ark.preinstall : Get what version of Java might be installed] 
changed: [deployTarget]

```
(note there are only 2 changes).

Kernel semaphores seem to have been set according to the documentation:
```
[sasinst@sasviya35 pre-install-playbook]$ grep kernel.sem /etc/sysctl.conf
kernel.sem=512  32000   256     1024
[sasinst@sasviya35 pre-install-playbook]$
```
I rebooted the machine to be sure but still get the same result.

**Comment by erharb** [comment]
This is more an an ansible-ism where certain modules are written to inherently understand changed versus ok, the latter meaning the expected state is already met.

However in the tasks you pointed are they are using the shell module to execute arbitrary commands on the remote host, which doesn't provide this inherent capability automatically, it would have to be explicitly code for each shell/command task using the "[changed_when](https://docs.ansible.com/ansible/latest/user_guide/playbooks_error_handling.html#overriding-the-changed-result)" parameter.

So it is possible to make this change, but there'd possibly be many more other command/shell tasks, and I'd view it as more of a feature request than a bug.
