### ISSUE TITLE
Viya 3.4 installation failure via ansible

### ISSUE THREAD

**Issue by naveengupta218** [sassoftware/viya-ark#37]
Hi,

I am getting below error message when installing viya 3.4 using ansible. Here is the error:

TASK [foundation-ensure-port-availability : Verify that SAS Object Spawner port is available] *************
fatal: [viyaCore]: FAILED! => {"changed": false, "elapsed": 5, "msg": "Timeout when waiting for 127.0.0.1:8591 to stop."}

But on core server, port is listening: 
[sas@viya-sbx-core0 ~]$ netstat -an | grep 8591
tcp6       0      0 :::8591                 :::*                    LISTEN
udp        0      0 10.123.35.240:48591     10.123.0.2:53           ESTABLISHED

**Comment by erharb** [comment]
This doesn't appear to be a Viya ARK specific issue? If it is please clarify which playbook you are using and which release was downloaded.

If is not Viya ARK specific, please contact SAS Technical Support for general Viya deployment issues.

**Comment by naveengupta218** [comment]
Hi Eric,

I am re-installing viya 3.4 again after ugrading 3.4 to 3.5 version couple of months ago in our sandbox environment. Before re-installing 3.4, I have cleaned up /opt/sas folder on all servers (2 controllers, 1 core and 2 workers) and also removed /etc/init.d on core server only and trying to re-install it.

Is there any other cleanup required before installing 3.4 again?

How to find version of playbook? I downloaded it on Oct 30th 2019

Regards,
Naveen Gupta
SAS Administrator/ SAS Administrateur
Tata Consultancy Services Limited

Farm Credit Canada / Financement agricole Canada
Tel/Tél.: 416-605-7349
E-mail/Courriel: naveen.gupta@fcc-fac.ca<mailto:naveen.gupta@fcc-fac.ca>
FCC social media<https://www.fcc-fac.ca/en/about-fcc/social-media.html> / Médias sociaux FAC<https://www.fcc-fac.ca/fr/a-propos-de-FAC/medias-sociaux.html>

Subscribe to FCC e-messages<http://fcc-fac.us4.list-manage1.com/subscribe?u=ba9d3e2cc376750a4ead6d282&id=ec8f259c3e> / S’abonner à la liste d’envoi de messages électroniques de FAC<http://fac-fcc.us4.list-manage.com/subscribe?u=ba9d3e2cc376750a4ead6d282&id=f6f4983c50>

Advancing the business of agriculture. Pour l’avenir de l’agroindustrie.

**Comment by erharb** [comment]
The Viya ARK is a set of optional, ancillary tools for use with administering Viya deployments, which is separate from the playbooks used to deploy or clean a Viya order.

The SAS supplied deploy-cleanup playbook is what should be used to properly clean a deployment. But this would imply a general Viya deployment issue, and for that the quickest resolution to your issue would be to contact SAS Technical Support please.
