### ISSUE TITLE
pause for confirmation viya-services-stop.yml

### ISSUE THREAD

**Issue by benformosa** [sassoftware/viya-ark#41]
The [viya-mmsu/viya-services-stop.yml](https://github.com/sassoftware/viya-ark/blob/master/playbooks/viya-mmsu/viya-services-stop.yml) playbook could include a pause to give administrators a chance to confirm that they want to proceed.

I use these playbooks for managing our environment, and want to add a safety net in case I accidentally run the stop playbook instead of status.

It should be easy enough to adapt the task from the [pre.pause](https://github.com/sassoftware/viya-ark/blob/master/playbooks/pre-install-playbook/roles/viya-ark.preinstall/tasks/pre.pause.yml) section of the preinstall role.
I'll raise a PR when I can.

**Comment by AlissaSchleich** [comment]
I have opened a review of this suggestion with our development team.   We will implement if we can.

**Comment by AlissaSchleich** [comment]
Thanks for using Viya-Ark
