### ISSUE TITLE
Need capability to start | stop | restart service groups instead of all services

### ISSUE THREAD

**Issue by andybouts** [sassoftware/viya-ark#44]
I've had the recent opportunity of restarting CAS on my 3 worker cluster several times.  It's easy and quick enough to do it directly on the hosts ... but I had a few minutes this morning and started searching to see if the Viya-ARK MMSU had the capability to restart only CAS instead of all Viya services.  Although I can restart CAS in about 5 mins, it takes about 60-70 mins to restart all services with the MMSU (so that's not an option).  It does not seem that there's an option to restart my CAS services (perhaps through the use of tags or some other parameter).  I would like to see the ability to restart service groups as well as individual services (for example, the ability to only restart SASLogon).

**Comment by erharb** [comment]
Currently that was the intention of the script to only handle full stops and starts, because stopping and starting individual services can really complicate things if not done properly so it was decided not to at the time of design.

**Comment by andybouts** [comment]
I would respectfully request that a few of the most common types of restarts as groups of services be considered ... perhaps starting with the CAS service.
