### ISSUE TITLE
Option to run Hotfix report only

### ISSUE THREAD

**Issue by alan-demarq** [sassoftware/viya-ark#45]
Using `Viya35-ark-1.2` , is there a way to just run the Hotfix section of the Deployment Report - is that possible using the current code?

A useful enhancement to the deployment report?

**Comment by kevinlinglesas** [comment]
I only see the current option to exclude hotfix info.   We can take under consideration your suggestion and perhaps add something like -e “hotfix_report_only=True”.

**Comment by erharb** [comment]
The hotfix part of the report relies on the RPM data being gathered, which is the majority of what the deployment report shows. I'm not sure there would be a benefit of showing partial report when there's not much more than that in the report.

**Comment by alan-demarq** [comment]
> The hotfix part of the report relies on the RPM data being gathered, which is the majority of what the deployment report shows. I'm not sure there would be a benefit of showing partial report when there's not much more than that in the report.

I'm thinking along the lines of when I'm likely to run this report:
The Machines section would be provided to the client after installation - they can see the machines & what microservices are installed where for example.
I'd see the Hotfix section being run regularly to then form the basis of documenting the ongoing maintenance of the platform.

I can see the dependency in the underlying data & the hotfix element by itself would be a welcome enhancement.

**Comment by AlissaSchleich** [comment]
I have entered a request for this feature.   It will be taken into consideration when we prioritize enhancements to current tools.

Thanks for your suggestion.
