### ISSUE TITLE
SFTP fails to copy viya-svs.sh to /tmp /.... on remote machines

### ISSUE THREAD

**Issue by 68wooley** [sassoftware/viya-ark#47]
Trying to run any of these playbooks results in an error as the SFTP command to copy viya-svs.sh to /tmp/.... on the remote machines is silently failing. The subsequent calls to execute viya-svs.sh fails with a "No such file or directory" error.

I've tried this on both a on-prem customer set up and on internal SAS exnet servers.
[start-stop-failures.txt](https://github.com/sassoftware/viya-ark/files/4361892/start-stop-failures.txt)

**Comment by erharb** [comment]
"/bin/sh: /tmp/.grrobi.ansible/ansible-tmp-1584740389.07-35014013646374/viya-svs.sh: /bin/bash^M: bad interpreter: No such file or directory"

looks like windows line endings made it to your downloads of Viya ARK, sometimes cloning on windows machines injects windows line endings if you did it that way

**Comment by 68wooley** [comment]
That was the problem - recursive dos2unix fixed it. Thnaks.
