### ISSUE TITLE
Deployment Report - Use host_vars

### ISSUE THREAD

**Issue by mawamb** [sassoftware/viya-ark#48]
I've noticed the deployment report uses the FQDN of the machine and not necessarily the values entered in host_vars if it exists. This can cause confusion in the report since certain aliases/hostname may have been used in host_vars per the customer requirements.

**Comment by AlissaSchleich** [comment]
I apologize for the delay in responding.  
I am opening a development ticket for this issue.   We will be looking at a way to fix the report so that it is more clear.
