### ISSUE TITLE
MMSU - doesn't use host_vars

### ISSUE THREAD

**Issue by mawamb** [sassoftware/viya-ark#50]
The URL listing in MMSU doesn't use the host_vars values that was used during deploying which would end up being used to surface the URLs.  So MMSU lists URLs that are not using the proper hostnames (instead some other FQDN) and thus providing the wrong URL to use.

**Comment by cuddlehub** [comment]
MMSU gets in the inventory.ini [httpproxy] and then does the hostname -f to get the fully qualified name. 
  # The httpproxy host group contains HTTP Proxy Server.
  [httpproxy]
  deployTarget

Can you be more specific why it doesn't work in your environment?

**Comment by mawamb** [comment]
Using [host_vars](https://go.documentation.sas.com/?docsetId=dplyml0phy0lax&docsetTarget=n11nt9q5r1i9mun1e7m2chgxgyii.htm&docsetVersion=3.5&locale=en#) is a way to override the hostnames the deployment would use by default (i.e. hostname -f) in case you have multiple NICs or just need to use a different alias/hostname than "hostname -f." So in my case I used an alias in host_vars, but MMSU used "hostname -f" for the URLs listing, which a customer may use the incorrect one and get TLS errors in the browser for example.

**Comment by erharb** [comment]
With multiple NIC I don't think we can just assume everyone would use what is in ansible host_vars for both how they access the Viya service URLs and for ansible ssh purposes.

I'm thinking we could instead reference the appropriate variable input used to define during Viya deployment which NIC was selected for routing service URLs?

**Comment by mawamb** [comment]
But my variable in inventory.ini also uses the alias and not the output of hostname -f.  So shouldn't I have seen the proper hostname in the URL list?

I'm mainly speaking about the URLs list at the very end of the MMSU output should use the hostname used in inventory.ini or host_vars because that's the hostname that would be used for TLS certs, especially if you use customer generated certs and the CN/SANs are the aliases and not the FQDN in hostname -f.

**Comment by erharb** [comment]
I understand your environment, I'm just thinking there could be other environments out there which use separate host/IP for ssh traffic vs. http traffic.
