### ISSUE TITLE
Can't run pre_install_playbook due to sudo problem.

### ISSUE THREAD

**Issue by ken-sys** [sassoftware/viya-ark#51]
Hi,
I'm using  this version :  ## Viya35-ark-1.3 - April 1, 2020

I'm a sudo user on a new server.  I run into a an error " " when running the pre_install_playbook, I get an error about the sudo password.   

Can you advise on how to proceed? Thank!

bash-4.2$ ansible-playbook -i ./pre-install.inventory.ini viya_pre_install_playbook.yml --check

PLAY [localhost] ..snip..
TASK [Gathering Facts]  ..snip..
ok: [localhost]
PLAY [sas_all]  ..snip..
TASK [Gathering Facts] ..snip..

fatal: [deployTarget]: FAILED! => {"changed": false, "module_stderr": "**sudo: a password is required**\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
        to retry, use: --limit @/sas/viya-ark/playbooks/pre-install-playbook/viya_pre_install_playbook.retry

PLAY RECAP  ..snip..
deployTarget               : ok=0    changed=0    unreachable=0    failed=1
localhost                  : ok=1    changed=0    unreachable=0    failed=0

**Comment by erwangranger** [comment]
have you tried it with the `--ask-become-pass` option? 

the entire command would then be: 

```bash
ansible-playbook -i ./pre-install.inventory.ini viya_pre_install_playbook.yml --check --ask-become-pass
```

And it would then prompt you for the sudo password, i.e. the password of you **current** account. 

More info and options available [here](https://docs.ansible.com/ansible/latest/user_guide/become.html#become-command-line-options)

**Comment by ken-sys** [comment]
Thanks for the parameter - that worked. Sorry for the late reply. This has been very helpful.
