### ISSUE TITLE
"basic connection test" fails in viyaldapvalidator.yml without specifying the -b option

### ISSUE THREAD

**Issue by wweghe** [sassoftware/viya-ark#52]
Hi,

I'm testing a setup to an MS AD, and the basic connection test : 
    shell: "{{ldapsearchstring_bind}} -z {{sizelimit}}"
fails when I run the playbook.
Error : 0000202B: RefErr: DSID-031007F9, data 0, 1 access points

When I add the basedn option : 
    shell: "{{ldapsearchstring_bind}} -z {{sizelimit}} -b {{ldap_group_basedn}} "
all tests pass fine without error

**Comment by AlissaSchleich** [comment]
I apologize for the delay in responding.   We are trying to reproduce the issue.

**Comment by kevinlinglesas** [comment]
Hi @wweghe .   Again, we apologize for the delay.   We needed to seek out some LDAP expertise from another developer who indicates that if userDN is not configured in the LDAP, this issue usually occurs.    Can you check with the customer to see if userDN has been configured in their LDAP server?

This reference link was also offered by the developer investigating this issue:
https://social.technet.microsoft.com/Forums/windowsserver/en-US/2ffffd43-a9db-4060-850c-e1e40b017abe/ldap-error?forum=winserverDS

**Comment by kevinlinglesas** [comment]
The use of ldap_group_basedn as a parameter in the "basic connection test" will be added for the next release of Viya ARK.   Once released, this issue will be closed.

**Comment by kevinlinglesas** [comment]
Release https://github.com/sassoftware/viya-ark/releases/tag/Viya35-ark-1.6 addressed this issue.  Closing.
