### ISSUE TITLE
MMSU doesn't cleanup stray process

### ISSUE THREAD

**Issue by mawamb** [sassoftware/viya-ark#53]
When stopping the services, the MMSU doesn't seem to be able to get rid of a stray process. I have a track open as well on this: https://sirius.na.sas.com/Sirius/ShowTrack.aspx?trknum=7613062387

**When I first executed the MMSU, I got the following error:**

TASK [Display SAS stray processes] ****************************************************************

fatal: [sasmas]: FAILED! => {
    "msg": [
        "Please examine the following stray process(es)",
        "If enable_stray_cleanup=true, process will be cleaned up automatically",
        "except database processes which require fix manually to avoid data corruption.",
        "This playbook can be rerun to clean up the child processes.",
        [
            "sas       1151     1  0 Apr16 ?        00:05:41 /usr/lib/jvm/jre-1.8.0/bin/java -XX:MinHeapFreeRatio=15 -Xss256k -Dendpoints.metrics.enabled=true -XX:MaxDirectMemorySize=64m -Dspring.cloud.consul.discovery.healthCheckCriticalTimeout=2h -XX:NewSize=20m -DuseServerCipherSuitesOrder=true -Dendpoints.enabled=false -Djavax.xml.XMLConstants.FEATURE_SECURE_PROCESSING=true -javaagent:/opt/sas/viya/home/libexec/filesystem-init-agent.jar -Djavax.net.ssl.trustStore=/opt/sas/viya/config/etc/SASSecurityCertificateFramework/cacerts/trustedcerts.jks -Dserver.port=0 -Dspring.cloud.consul.discovery.instanceId=sasstudio-10-23-36-87 -Djava.security.egd=file:/dev/urandom -Xmx196m -DjvmRoute=sasstudio-10-23-36-87 -Dsas.vault.pki.reuseValidCertificate=false -Djava.io.tmpdir=/opt/sas/viya/config/tmp/sas-sasstudio -Xms60m -XX:CICompilerCount=2 -javaagent:/opt/sas/viya/home/libexec/aspectjweaver.jar -Dserver.ssl.ciphers=TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 -XX:MaxHeapFreeRatio=40 -Dhttps.cipherSuites=TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 -Djavax.net.ssl.trustStoreType=jks -Djdk.nio.maxCachedBufferSize=256k -Dserver.tomcat.internal-proxies=(fe80|fd[0-9a-fA-F]{2})(:{1,2}[0-9a-fA-F]{0,4}){0,7}(%[0-9a-zA-Z]+)?$|::1|0:0:0:0:0:0:0:1|10\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}|192\\.168\\.\\d{1,3}\\.\\d{1,3}|169\\.254\\.\\d{1,3}\\.\\d{1,3}|127\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}|172\\.1[6-9]{1}\\.\\d{1,3}\\.\\d{1,3}|172\\.2[0-9]{1}\\.\\d{1,3}\\.\\d{1,3}|172\\.3[0-1]{1}\\.\\d{1,3}\\.\\d{1,3} -Dsun.security.krb5.msinterop.kstring=true -Dendpoints.health.enabled=true -jar /opt/sas/viya/home/libexec/sas-studio-lite-app-5.2.212.war"
        ]
    ]
}

**Then I ran stop again, ensuring "enable_stray_cleanup: true" is set. Then I get:**

TASK [SAS Infrastructure Data Server - postgres] **************************************************
fatal: [sasmas]: FAILED! => {"changed": true, "msg": "non-zero return code", "rc": 1, "stderr": "Shared connection to g2n1-sas-viya-va.ultainc.lcl closed.\r\n", "stderr_lines": ["Shared connection to g2n1-sas-viya-va.ultainc.lcl closed."], "stdout": "Error retrieving members: Get https://localhost:8501/v1/agent/members?segment=_all: dial tcp [::1]:8501: connect: connection refused\r\nERROR: consul has error, please check consul log.\r\n", "stdout_lines": ["Error retrieving members: Get https://localhost:8501/v1/agent/members?segment=_all: dial tcp [::1]:8501: connect: connection refused", "ERROR: consul has error, please check consul log."]}

I'm on the latest version: Viya35-ark-1.3 - April 1, 2020.

The process in question on the server:

viyadep@g2n1-lvyams01 ~]$ ps -efa | grep viya
sas       1151     1  0 Apr16 ?        00:06:04 /usr/lib/jvm/jre-1.8.0/bin/java -XX:MinHeapFreeRatio=15 -Xss256k -Dendpoints.metrics.enabled=true -XX:MaxDirectMemorySize=64m -Dspring.cloud.consul.discovery.healthCheckCriticalTimeout=2h -XX:NewSize=20m -DuseServerCipherSuitesOrder=true -Dendpoints.enabled=false -Djavax.xml.XMLConstants.FEATURE_SECURE_PROCESSING=true -javaagent:/opt/sas/viya/home/libexec/filesystem-init-agent.jar -Djavax.net.ssl.trustStore=/opt/sas/viya/config/etc/SASSecurityCertificateFramework/cacerts/trustedcerts.jks -Dserver.port=0 -Dspring.cloud.consul.discovery.instanceId=sasstudio-10-23-36-87 -Djava.security.egd=file:/dev/urandom -Xmx196m -DjvmRoute=sasstudio-10-23-36-87 -Dsas.vault.pki.reuseValidCertificate=false -Djava.io.tmpdir=/opt/sas/viya/config/tmp/sas-sasstudio -Xms60m -XX:CICompilerCount=2 -javaagent:/opt/sas/viya/home/libexec/aspectjweaver.jar -Dserver.ssl.ciphers=TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 -XX:MaxHeapFreeRatio=40 -Dhttps.cipherSuites=TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 -Djavax.net.ssl.trustStoreType=jks -Djdk.nio.maxCachedBufferSize=256k -Dserver.tomcat.internal-proxies=(fe80|fd[0-9a-fA-F]{2})(:{1,2}[0-9a-fA-F]{0,4}){0,7}(%[0-9a-zA-Z]+)?$|::1|0:0:0:0:0:0:0:1|10\.\d{1,3}\.\d{1,3}\.\d{1,3}|192\.168\.\d{1,3}\.\d{1,3}|169\.254\.\d{1,3}\.\d{1,3}|127\.\d{1,3}\.\d{1,3}\.\d{1,3}|172\.1[6-9]{1}\.\d{1,3}\.\d{1,3}|172\.2[0-9]{1}\.\d{1,3}\.\d{1,3}|172\.3[0-1]{1}\.\d{1,3}\.\d{1,3} -Dsun.security.krb5.msinterop.kstring=true -Dendpoints.health.enabled=true -jar /opt/sas/viya/home/libexec/sas-studio-lite-app-5.2.212.war
viyadep   5176 18326  0 20:29 pts/1    00:00:00 ps -efa

**Comment by cuddlehub** [comment]
This problem was fixed in the latest version dated: svs_label: 3.5.20200415

**Comment by harbdog** [comment]
Note that the fixed version hasn't yet been published to Github, it is forthcoming however
