### ISSUE TITLE
Pre-installation Playbook - report?

### ISSUE THREAD

**Issue by ken-sys** [sassoftware/viya-ark#55]
Does the Pre-installation Playbook create a report to view?
Or do we need to capture the scrolling output (which is a lot) and parse through that.

I don't see in the docs for this how to review the output.
https://github.com/sassoftware/viya-ark/tree/master/playbooks/pre-install-playbook

Thanks!

**Comment by erharb** [comment]
@ken-sys it does not create a report, just the ansible log output has the details

**Comment by ken-sys** [comment]
Thanks for the info.  I'll just log the output to a file.
