### ISSUE TITLE
pre-install failure for sudo

### ISSUE THREAD

**Issue by ken-sys** [sassoftware/viya-ark#56]
Hi,
My server has an existing LDAP account 'sas' that they use to manage the server.  I think that's messing my my Viya-ARK runs.  
I'm using the following to just run the 'usersudoaccess' task.

bobsmith@server99:pre-install-playbook $ ansible-playbook -i pre-install.inventory.ini  viya_pre_install_playbook.yml -e "use_pause=0" --check --ask-become-pass  --tags usersudoaccess
SUDO password:
...
TASK [viya-ark.preinstall : Ensure users are present] ****************************************************************************************************************************************************************
ok: [deployTarget] => (item={u'group': u'sas', u'name': u'cas', u'groups': u'sas', u'uid': 1010})

TASK [viya-ark.preinstall : Show the Users List] *********************************************************************************************************************************************************************
ok: [deployTarget] => {
    "usersearch_result": {
        "changed": false,
        "msg": "All items completed",
        "results": [
            {
                "_ansible_ignore_errors": true,
                "_ansible_item_label": {
                    "group": "sas",
                    "groups": "sas",
                    "name": "cas",
                    "uid": 1010
                },
                "_ansible_item_result": true,
                "_ansible_no_log": false,
                "_ansible_parsed": true,
                "changed": false,
                "cmd": "getent passwd cas",
                "delta": "0:00:00.007255",
                "end": "2020-04-29 16:29:33.169576",
                "failed": false,
                "invocation": {
                    "module_args": {
                        "_raw_params": "getent passwd cas",
                        "_uses_shell": true,
                        "argv": null,
                        "chdir": null,
                        "creates": null,
                        "executable": null,
                        "removes": null,
                        "stdin": null,
                        "warn": true
                    }
                },
                "item": {
                    "group": "sas",
                    "groups": "sas",
                    "name": "cas",
                    "uid": 1010
                },
                "rc": 0,
                "start": "2020-04-29 16:29:33.162321",
                "stderr": "",
                "stderr_lines": [],
                "stdout": "cas:x:1010:1009::/home/cas:/bin/bash",
                "stdout_lines": [
                    "cas:x:1010:1009::/home/cas:/bin/bash"
                ]
            }
        ]
    }
}

TASK [viya-ark.preinstall : Assert that User Exists] *****************************************************************************************************************************************************************
skipping: [deployTarget] => (item={'_ansible_parsed': True, 'stderr_lines': [], u'changed': False, u'stdout': u'cas:x:1010:1009::/home/cas:/bin/bash', '_ansible_item_result': True, u'delta': u'0:00:00.007255', 'stdout_lines': [u'cas:x:1010:1009::/home/cas:/bin/bash'], '_ansible_item_label': {u'group': u'sas', u'name': u'cas', u'groups': u'sas', u'uid': 1010}, u'end': u'2020-04-29 16:29:33.169576', '_ansible_no_log': False, 'failed': False, u'cmd': u'getent passwd cas', 'item': {u'group': u'sas', u'name': u'cas', u'groups': u'sas', u'uid': 1010}, u'stderr': u'', u'rc': 0, u'invocation': {u'module_args': {u'warn': True, u'executable': None, u'_uses_shell': True, u'_raw_params': u'getent passwd cas', u'removes': None, u'argv': None, u'creates': None, u'chdir': None, u'stdin': None}}, u'start': u'2020-04-29 16:29:33.162321', '_ansible_ignore_errors': True})

TASK [viya-ark.preinstall : capture the current user's actual sudo rights] *******************************************************************************************************************************************
 [WARNING]: Consider using 'become', 'become_method', and 'become_user' rather than running sudo

ok: [deployTarget]

TASK [viya-ark.preinstall : debug] ***********************************************************************************************************************************************************************************
ok: [deployTarget] => {
    "sudo_rights": {
        "changed": false,
        "cmd": "sudo -l",
        "delta": "0:00:00.040462",
        "end": "2020-04-29 16:29:34.662671",
        "failed": false,
        "rc": 0,
        "start": "2020-04-29 16:29:34.622209",
        "stderr": "",
        "stderr_lines": [],
        "stdout": "Matching Defaults entries for bobsmith on server99:\n    passprompt=\"(sudo) Password on %h: \", timestamp_timeout=30\n\nUser bobsmith may run the following commands on server99:\n    (root) ALL, !/bin/su, !/usr/local/bin/su, !/opt/freeware/bin/su, !/usr/bin/su, !/usr/sbin/visudo\n    (root) ALL, !/bin/su, !/usr/local/bin/su, !/opt/freeware/bin/su, !/usr/bin/su, !/usr/sbin/visudo",
        "stdout_lines": [
            "Matching Defaults entries for bobsmith on server99:",
            "    passprompt=\"(sudo) Password on %h: \", timestamp_timeout=30",
            "",
            "User bobsmith may run the following commands on server99:",
            "    (root) ALL, !/bin/su, !/usr/local/bin/su, !/opt/freeware/bin/su, !/usr/bin/su, !/usr/sbin/visudo",
            "    (root) ALL, !/bin/su, !/usr/local/bin/su, !/opt/freeware/bin/su, !/usr/bin/su, !/usr/sbin/visudo"
        ],
        "warnings": [
            "Consider using 'become', 'become_method', and 'become_user' rather than running sudo"
        ]
    }
}

TASK [viya-ark.preinstall : Check that we can impersonnate all 3 users] **********************************************************************************************************************************************
fatal: [deployTarget]: FAILED! => {"msg": "privilege output closed while waiting for password prompt:\nSorry, user bobsmith is not allowed to execute '/bin/sh -c echo BECOME-SUCCESS-izqqsbthvqhnandmjrfyrumqbayenodh; /usr/bin/python /var/tmp/ansible-tmp-1588192175.31-173865549484289/AnsiballZ_command.py' as cas on server99.\n"}
...ignoring

TASK [viya-ark.preinstall : Display the result of the Sudo search] ***************************************************************************************************************************************************
ok: [deployTarget] => {
    "checkuserpriv_status": {
        "failed": true,
        **"msg": "privilege output closed while waiting for password prompt:\nSorry, user bobsmith is not allowed to execute '/bin/sh -c echo BECOME-SUCCESS-izqqsbthvqhnandmjrfyrumqbayenodh; /usr/bin/python /var/tmp/ansible-tmp-1588192175.31-173865549484289/AnsiballZ_command.py' as cas on server99.\n"**
    }
}

...
PLAY RECAP ***********************************************************************************************************************************************************************************************************
deployTarget               : ok=7    changed=0    unreachable=0    failed=0
localhost                  : ok=1    changed=0    unreachable=0    failed=0

Do you think I have a config issue with Viya-ARK, or is my server needing a fix.  Some points:

bobsmith@server99:pre-install-playbook $ sudo -v

bobsmith@server99:pre-install-playbook $ sudo -l
Matching Defaults entries for bobsmith on server99:
    passprompt="(sudo) Password on %h: ", timestamp_timeout=30
User bobsmith may run the following commands on server99:
    (root) ALL, !/bin/su, !/usr/local/bin/su, !/opt/freeware/bin/su, !/usr/bin/su, !/usr/sbin/visudo
    (root) ALL, !/bin/su, !/usr/local/bin/su, !/opt/freeware/bin/su, !/usr/bin/su, !/usr/sbin/visudo

bobsmith@server99:pre-install-playbook $ cat /etc/group | grep sas
sas:x:1009:cas,sas

**Comment by kevinlinglesas** [comment]
Reviewing your post @ken-sys.

**Comment by kevinlinglesas** [comment]
@ken-sys, I've got a few more questions...

- Can you give me all of the steps previously executed wrt this env?   
- You seemed to imply multiple viya-ark runs.  Did you run viya-ark w/out check mode before?  
- How was viya-ark run the very first time?
- Are you being prompted for sudo password?  I see "SUDO password:". 
- Was this before any deployment to this env?   If a deployment, what's that environment like (single node, multi, etc)?  
- What version of Ansible and OS are you running on?   What version of Python?
- What do you get when you execute this command on the target machine(s)?
-- `printf "the user $(id) can access $(python --version 2>&1)"`

Thanks,
@kevinlinglesas

**Comment by ken-sys** [comment]
@kevinlinglesas thanks for the response!   Here's the info.

---Q: What release of viya-ark are you using?
bobsmith@server99:viya-ark $ head -n 5 CHANGELOG.md
...
## Viya35-ark-1.3 - April 1, 2020

---Q: Can you give me all of the steps previously executed wrt this env?
sudo yum update
sudo yum install java-1.8.0-openjdk   (needed for sas-orchestration tool)
sudo yum install -y python python-setuptools python-devel openssl-devel
sudo yum install -y python-pip gcc wget automake libffi-devel python-six htop
sudo pip install pip==19.3.1
sudo pip install setuptools==42.0.2
sudo pip install ansible==2.7.2
sudo reboot

---Q: You seemed to imply multiple viya-ark runs. Did you run viya-ark w/out check mode before?
Yes. Then I did a run without check mode. Of course I did get this error, but the other modules adjusted the OS settings, and I did a reboot.

---Q: How was viya-ark run the very first time?
cd /sas/viya-ark/playbooks/pre-install-playbook
ansible-playbook -vvv -i ./pre-install.inventory.ini viya_pre_install_playbook.yml --check --ask-become-pass

---Q: Are you being prompted for sudo password? I see "SUDO password:".
Yes. And if I flub the password, it won't run. So I know it's using the password.

---Q: Was this before any deployment to this env? If a deployment, what's that environment like (single node, multi, etc)?
This was a new vanilla server from our I.T.  It's a single machine Viya.
A big problem is they put a service account to our Active Directory/LDAP called 'sas'. It may be the root of this issue.

---Q: What version of Ansible and OS are you running on? What version of Python?
bobsmith@server99:~ $ ansible --version
ansible 2.7.2
  config file = None
  configured module search path = [u'/r/ge.prd.magacorp.com/vol/vol420/u42/bobsmith/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Jun 11 2019, 14:33:56) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]

OS: RHEL 7.7, 128 GB RAM, 16 cores.

---Q: What do you get when you execute this command on the target machine(s)?
-- printf "the user $(id) can access $(python --version 2>&1)"

bobsmith@server99:~ $ printf "the user $(id) can access $(python --version 2>&1)"
the user uid=10218(bobsmith) gid=104(unix_education) groups=104(unix_education),2124(EDULDSA) context=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 can access Python 2.7.5

**Comment by kevinlinglesas** [comment]
@ken-sys , like we discussed on the phone I think the crux of your issue is when user executing playbook doesn't have sufficient sudo permissions.   you also really need passwordless sudo as well to avoid having to enter sudo password and use ask-become-pass option.

Your `/etc/sudoers` is reflecting not being able to become root (various `!/<path>/su` seen from `sudo -l`).  You will have to get someone with root access to fix this for you with visudo editing of sudoers to include something like:
`bobsmith    ALL=(ALL)       NOPASSWD: ALL`

That will take care of the passwordless issue as well.

I was not able to replicate your failure due to have the above sudo config in my env.   Note also though that the failure of the task you encountered is also by design ignored, so it will not prevent you from moving forward.    I think you have been able to proceed with deployments and such.  Am I right?

**Comment by ken-sys** [comment]
Thanks for the detailed info!
I was able to work out the lack of full sudo access with my IT.

Now this runs:
/bin/sh -c "sudo -H -S -u sas /bin/sh -c 'date; id'"      

Also the Viya-ARK tool now passes the user access module (here's the   command):      

ansible-playbook -i pre-install.inventory.ini viya_pre_install_playbook.yml   -e "use_pause=0" --check --ask-become-pass --tags usersudoaccess     

Thanks for the assist!
