### ISSUE TITLE
MMSU: Issue starting services

### ISSUE THREAD

**Issue by sasayd** [sassoftware/viya-ark#57]
I have a 3-tier deployment, deployTarget, cas-controller, cas-worker.  Ansible, all the SAS services are on deployTarget.  Why is the line below failing for the SAS Infrastructure Data Server which is only on deployTarget? 

The cas-controller server has cascontroller, consul installed and cas-worker has consul installed.  

TASK [Start SAS Infrastructure Data Server Consul Template] *****************************************************
fatal: [deployTarget]: FAILED! => {"msg": "The conditional check 'INVOCATION_VARIABLES[inventory_hostname] is defed. The error was: error while evaluating conditional (INVOCATION_VARIABLES[inventory_hostname] is defined): 'SASOT' is undefined\n\nThe error appears to have been in '/mnt/resource/sas_repos/sas_viya_playbook/viya-ark/playboosu/viya-services-start.yml': line 70, column 9, but may\nbe elsewhere in the file depending on the exact syntax pnThe offending line appears to be:\n\n    - block:\n      - name: Start SAS Infrastructure Data Server Consul Tem     ^ here\n"}
fatal: [cas-worker]: FAILED! => {"msg": "The conditional check 'INVOCATION_VARIABLES[inventory_hostname] is defin. The error was: error while evaluating conditional (INVOCATION_VARIABLES[inventory_hostname] is defined): 'SAS_C' is undefined\n\nThe error appears to have been in '/mnt/resource/sas_repos/sas_viya_playbook/viya-ark/playbooks/viya-services-start.yml': line 70, column 9, but may\nbe elsewhere in the file depending on the exact syntax prohe offending line appears to be:\n\n    - block:\n      - name: Start SAS Infrastructure Data Server Consul Templ   ^ here\n"}
fatal: [cas-controller]: FAILED! => {"msg": "The conditional check 'INVOCATION_VARIABLES[inventory_hostname] is diled. The error was: error while evaluating conditional (INVOCATION_VARIABLES[inventory_hostname] is defined): 'SROOT' is undefined\n\nThe error appears to have been in '/mnt/resource/sas_repos/sas_viya_playbook/viya-ark/playbmmsu/viya-services-start.yml': line 70, column 9, but may\nbe elsewhere in the file depending on the exact syntaxn\nThe offending line appears to be:\n\n    - block:\n      - name: Start SAS Infrastructure Data Server Consul T       ^ here\n"}

**Comment by erharb** [comment]
Most likely either the vars.yml is not setup correctly or you are trying to run the playbook from the wrong location and it cannot access the INVOCATION_VARIABLES section of your vars.yml used when you deployed Viya with site.yml.

Can you confirm you are invoking the viya-services-start.yml per the instructions here from sas_viya_playbook directory:
https://github.com/sassoftware/viya-ark/tree/master/playbooks/viya-mmsu#requirements-for-running-the-mmsu-playbooks

`ansible-playbook viya-ark/playbooks/viya-mmsu/viya-services-start.yml`

**Comment by sasayd** [comment]
Hi,
Thanks that was the problem. I was not running from that folder.


Thanks,
Annette

**Comment by erharb** [comment]
No problem!
