### ISSUE TITLE
Unable to start all services in Viya 3.5 deployment 

### ISSUE THREAD

**Issue by brianmbennett** [sassoftware/viya-ark#58]
Hi. We are unable to start all services on our Viya 3.5 deployment using playbooks/viya-mmsu/viya-services-start.yml.

We are using viya-ark version: 3.5.20200318 and are running viya-services-start.yml via dzdo using the following command:
`[dgupta1sec@usbntldcsasap33 sas_viya_playbook]$ dzdo -u svcsasansibledev ansible-playbook viya-ark-latest/playbooks/viya-mmsu/viya-services-start.yml`

The deployment consists of:
- mas-runtime 
- cas-worker-1
- cas-worker-2     
- http-proxy           
- deployTarget-1    
- deployTarget-2   

We are getting failures on deployTarget-1 and deployTarget-2.

Attached are:
1. The inventory.ini file
2. The viya-services-vars.yml
3. The console output when running viya-services-start.yml

We have also opened a SAS TS ticket (7613081934) for this issue. Thank you for any guidance.
-Brian

[Files.zip](https://github.com/sassoftware/viya-ark/files/4618492/Files.zip)

**Comment by erharb** [comment]
It appears the failures are entirely within sas-viya-all-services which is not a Viya ARK provided script but rather provided with the SAS Viya deployment.  Judging by the output of sas-viya-all-services the failures appear all related to SAS Programming Environment and CAS. You will want to continue to work with SAS Technical Support on this one.

```
fatal: [deployTarget-2]: FAILED! => {"attempts": 3, "changed": true, "cmd": "/etc/init.d/sas-viya-all-services start", "delta": "0:09:23.228271", "end": "2020-05-12 15:22:05.184216", "rc": 0, "start": "2020-05-12 15:12:41.955945", "stderr": "", "stderr_lines": [], "stdout": "sas-viya-consul-default is already started
Starting sas-viya-connect-default
Starting sas-viya-spawner-default
There are still 2 services starting.  Waiting for them to be ready - Sleeping...
There are still 2 services starting.  Waiting for them to be ready - Sleeping...
There are still 2 services starting.  Waiting for them to be ready - Sleeping...
There are still 2 services starting.  Waiting for them to be ready - Sleeping...
There are still 2 services starting.  Waiting for them to be ready - Sleeping...
WARNING: sas-viya-connect-default has been started and died 4 times.  It will not be restarted.
         Other services may fail to start due to this.  Check logs, remedy the problem and try again.
WARNING: sas-viya-spawner-default has been started and died 4 times.  It will not be restarted.
         Other services may fail to start due to this.  Check logs, remedy the problem and try again.

fatal: [deployTarget]: FAILED! => {"attempts": 3, "changed": true, "cmd": "/etc/init.d/sas-viya-all-services start"
...
"WARNING: sas-viya-cascontroller-default has been started and died 4 times.  It will not be restarted.",
 "         Other services may fail to start due to this.  Check logs, remedy the problem and try again."
```
