### ISSUE TITLE
After Linux Rhel patching we are seeing issues with viya-services-status.yml , alsl start script had issues, so had to restart sas services manually

### ISSUE THREAD

**Issue by svemuri123** [sassoftware/viya-ark#60]
2.	Looks like something is wrong with the viya-ark script, even though all the services are up and everything is working , I just tried to run the script to verify but its failing with syntax error in the script 

[buildadmin@AZP-SASVIYA-N00 postgres]$ /usr/bin/ansible-playbook /opt/sasdata/sas_viya_playbook/viya-ark/playbooks/viya-mmsu/viya-services-status.yml -i /opt/sa                                                                             sdata/updates/sas_viya_playbook/inventory.ini

PLAY [localhost] ***************************************************************

TASK [Gathering Facts] *********************************************************
ok: [localhost]

TASK [Determine if groups with hyphens need mapped using underscores] **********
skipping: [localhost] => (item={'key': 'all', 'value': [u'deployTarget', u'worker01', u'worker02', u'worker03', u'worker04']})
skipping: [localhost] => (item={'key': u'HomeServices', 'value': [u'deployTarget ']})
skipping: [localhost] => (item={'key': u'ScoringServices', 'value': [u'deployTarget']})
skipping: [localhost] => (item={'key': u'consul', 'value': [u'deployTarget']})
skipping: [localhost] => (item={'key': u'sas_all', 'value': [u'deployTarget', u'worker01', u'worker02', u'worker03', u'worker04']})
skipping: [localhost] => (item={'key': u'AdminServices', 'value': [u'deployTarget']})
skipping: [localhost] => (item={'key': u'httpproxy', 'value': [u'deployTarget']} )
skipping: [localhost] => (item={'key': u'ThemeServices', 'value': [u'deployTarget']})
skipping: [localhost] => (item={'key': u'ModelServices', 'value': [u'deployTarget']})
skipping: [localhost] => (item={'key': u'ComputeServices', 'value': [u'deployTarget']})
skipping: [localhost] => (item={'key': u'GraphBuilderServices', 'value': [u'deployTarget']})
skipping: [localhost] => (item={'key': u'ReportServices', 'value': [u'deployTarget']})
skipping: [localhost] => (item={'key': u'StudioViya', 'value': [u'deployTarget']})
skipping: [localhost] => (item={'key': 'ungrouped', 'value': []})
skipping: [localhost] => (item={'key': u'sas_casserver_secondary', 'value': []})                                                                             
skipping: [localhost] => (item={'key': u'ReportViewerServices', 'value': [u'deployTarget']})
skipping: [localhost] => (item={'key': u'pgpoolc', 'value': [u'deployTarget']})
skipping: [localhost] => (item={'key': u'sas_casserver_primary', 'value': [u'deployTarget']})
skipping: [localhost] => (item={'key': u'sasdatasvrc', 'value': [u'deployTarget']})
skipping: [localhost] => (item={'key': u'ComputeServer', 'value': [u'deployTarget']})
skipping: [localhost] => (item={'key': u'CommandLine', 'value': [u'deployTarget']})
skipping: [localhost] => (item={'key': u'CoreServices', 'value': [u'deployTarget']})
skipping: [localhost] => (item={'key': u'CognitiveComputingServices', 'value': [u'deployTarget']})
skipping: [localhost] => (item={'key': u'Operations', 'value': [u'deployTarget']})
skipping: [localhost] => (item={'key': u'configuratn', 'value': [u'deployTarget']})
skipping: [localhost] => (item={'key': u'sas_casserver_worker', 'value': [u'worker01', u'worker02', u'worker03', u'worker04']})
skipping: [localhost] => (item={'key': u'CASServices', 'value': [u'deployTarget']})
skipping: [localhost] => (item={'key': u'programming', 'value': [u'deployTarget']})
skipping: [localhost] => (item={'key': u'rabbitmq', 'value': [u'deployTarget']})                                                        
skipping: [localhost] => (item={'key': u'DataServices', 'value': [u'deployTarget']})

PLAY [sas_all] *****************************************************************

TASK [Capture all SAS services status from Consul] *****************************
ok: [worker02]
ok: [worker03]
ok: [worker04]
ok: [worker01]
ok: [deployTarget]

TASK [set_fact] ****************************************************************
ok: [deployTarget]
ok: [worker01]
ok: [worker02]
ok: [worker03]
ok: [worker04]

TASK [Set consul flag] *********************************************************
fatal: [deployTarget]: FAILED! => {"msg": "The conditional check 'svas_status.stdout|search('Consul is down')' failed. The error was: template error while templ                                                                             ating string: no filter named 'search'. String: {% if svas_status.stdout|search('Consul is down') %} True {% else %} False {% endif %}\n\nThe error appears to b                                                                             e in '/opt/sasdata/sas_viya_playbook/viya-ark/playbooks/viya-mmsu/viya-services-status.yml': line 27, column 7, but may\nbe elsewhere in the file depending on t                                                                             he exact syntax problem.\n\nThe offending line appears to be:\n\n\n    - name: Set consul flag\n      ^ here\n"}
fatal: [worker01]: FAILED! => {"msg": "The conditional check 'svas_status.stdout|search('Consul is down')' failed. The error was: template error while templatin                                                                             g string: no filter named 'search'. String: {% if svas_status.stdout|search('Consul is down') %} True {% else %} False {% endif %}\n\nThe error appears to be in                                                                              '/opt/sasdata/sas_viya_playbook/viya-ark/playbooks/viya-mmsu/viya-services-status.yml': line 27, column 7, but may\nbe elsewhere in the file depending on the e                                                                             xact syntax problem.\n\nThe offending line appears to be:\n\n\n    - name: Set consul flag\n      ^ here\n"}
fatal: [worker02]: FAILED! => {"msg": "The conditional check 'svas_status.stdout|search('Consul is down')' failed. The error was: template error while templatin                                                                             g string: no filter named 'search'. String: {% if svas_status.stdout|search('Consul is down') %} True {% else %} False {% endif %}\n\nThe error appears to be in                                                                              '/opt/sasdata/sas_viya_playbook/viya-ark/playbooks/viya-mmsu/viya-services-status.yml': line 27, column 7, but may\nbe elsewhere in the file depending on the e                                                                             xact syntax problem.\n\nThe offending line appears to be:\n\n\n    - name: Set consul flag\n      ^ here\n"}
fatal: [worker03]: FAILED! => {"msg": "The conditional check 'svas_status.stdout|search('Consul is down')' failed. The error was: template error while templatin                                                                             g string: no filter named 'search'. String: {% if svas_status.stdout|search('Consul is down') %} True {% else %} False {% endif %}\n\nThe error appears to be in                                                                              '/opt/sasdata/sas_viya_playbook/viya-ark/playbooks/viya-mmsu/viya-services-status.yml': line 27, column 7, but may\nbe elsewhere in the file depending on the e                                                                             xact syntax problem.\n\nThe offending line appears to be:\n\n\n    - name: Set consul flag\n      ^ here\n"}
fatal: [worker04]: FAILED! => {"msg": "The conditional check 'svas_status.stdout|search('Consul is down')' failed. The error was: template error while templatin                                                                             g string: no filter named 'search'. String: {% if svas_status.stdout|search('Consul is down') %} True {% else %} False {% endif %}\n\nThe error appears to be in                                                                              '/opt/sasdata/sas_viya_playbook/viya-ark/playbooks/viya-mmsu/viya-services-status.yml': line 27, column 7, but may\nbe elsewhere in the file depending on the e                                                                             xact syntax problem.\n\nThe offending line appears to be:\n\n\n    - name: Set consul flag\n      ^ here\n"}

PLAY RECAP *********************************************************************
deployTarget               : ok=2    changed=0    unreachable=0    failed=1    s                                                                             kipped=0    rescued=0    ignored=0
localhost                  : ok=1    changed=0    unreachable=0    failed=0    s                                                                             kipped=1    rescued=0    ignored=0
worker01                   : ok=2    changed=0    unreachable=0    failed=1    s                                                                             kipped=0    rescued=0    ignored=0
worker02                   : ok=2    changed=0    unreachable=0    failed=1    s                                                                             kipped=0    rescued=0    ignored=0
worker03                   : ok=2    changed=0    unreachable=0    failed=1    s                                                                             kipped=0    rescued=0    ignored=0
worker04                   : ok=2    changed=0    unreachable=0    failed=1    s                                                                             kipped=0    rescued=0    ignored=0

Below you could see all the services are up:
[buildadmin@AZP-SASVIYA-N00 postgres]$ sudo /etc/init.d/sas-viya-all-services status
Getting service info from consul...
  Service                                            Status     Host               Port     PID
  sas-viya-consul-default                            up         N/A                 N/A  114557
  sas-viya-vault-default                             up         10.33.0.51         8200  124122
  sas-viya-sasdatasvrc-postgres-node0-ct-pg_hba      up         N/A                 N/A   30706
  sas-viya-sasdatasvrc-postgres-node0-ct-postgresql  up         N/A                 N/A   30728
  sas-viya-sasdatasvrc-postgres-pgpool0-ct-pcp       up         N/A                 N/A   30759
  sas-viya-sasdatasvrc-postgres-pgpool0-ct-pgpool    up         N/A                 N/A   30784
  sas-viya-sasdatasvrc-postgres-pgpool0-ct-pool_hba  up         N/A                 N/A   30805
  sas-viya-sasdatasvrc-postgres-node0                up         N/A                 N/A   17755
  sas-viya-cascontroller-default                     up         N/A                 N/A   32690
  sas-viya-httpproxy-default                         up         N/A                 N/A   22647
  sas-viya-rabbitmq-server-default                   up         10.33.0.51         5671    None
  sas-viya-sasdatasvrc-postgres                      up         N/A                 N/A   17998
  sas-viya-sasstudio-default                         up         N/A                 N/A   32500
  sas-viya-spawner-default                           up         N/A                 N/A   32938
  sas-viya-runlauncher-default                       up         10.33.0.51        33313   33604
  sas-viya-alert-track-default                       up         10.33.0.51            0   34299
  sas-viya-authorization-default                     up         10.33.0.51        44698   34730
  sas-viya-cachelocator-default                      up         10.33.0.51        43820   34815
  sas-viya-cacheserver-default                       up         10.33.0.51        46259   34791
  sas-viya-configuration-default                     up         10.33.0.51        35694   34891
  sas-viya-identities-default                        up         10.33.0.51        34409   34939
  sas-viya-ops-agent-default                         up         10.33.0.51            0   34985
  sas-viya-ops-agentsrv-default                      up         10.33.0.51            0   35013
  sas-viya-saslogon-default                          up         10.33.0.51        44848   38288
  sas-viya-stream-evdm-default                       up         10.33.0.51            0   38162
  sas-viya-watch-log-default                         up         10.33.0.51            0   38212
  sas-viya-cas-management-default                    up         10.33.0.51        39916   43724
  sas-viya-files-default                             up         10.33.0.51        35693   43783
  sas-viya-folders-default                           up         10.33.0.51        37375   43806
  sas-viya-preferences-default                       up         10.33.0.51        39899   43879
  sas-viya-relationships-default                     up         10.33.0.51        36651   43916
  sas-viya-transformations-default                   up         10.33.0.51        36732   43965
  sas-viya-types-default                             up         10.33.0.51        39952   43981
  sas-viya-appregistry-default                       up         10.33.0.51        42781   51870
  sas-viya-audit-default                             up         10.33.0.51        41020   51845
  sas-viya-cas-access-management-default             up         10.33.0.51        39378   51915
  sas-viya-cas-formats-default                       up         10.33.0.51        45370   51970
  sas-viya-cas-license-default                       up         10.33.0.51        33534   52037
  sas-viya-casproxy-default                          up         10.33.0.51        33773   52126
  sas-viya-casrowsets-default                        up         10.33.0.51        39075   52122
  sas-viya-collections-default                       up         10.33.0.51        38282   52170
  sas-viya-comments-default                          up         10.33.0.51        35744   58476
  sas-viya-credentials-default                       up         10.33.0.51        35849   58515
  sas-viya-crossdomainproxy-default                  up         10.33.0.51        43063   58555
  sas-viya-dataflowexecutionprovider-default         up         10.33.0.51        36224   62013
  sas-viya-dataplans-default                         up         10.33.0.51        38132   62063
  sas-viya-datasources-default                       up         10.33.0.51        38798   62108
  sas-viya-datatables-default                        up         10.33.0.51        40135   62136
  sas-viya-deploymentBackup-default                  up         10.33.0.51        43627   62190
  sas-viya-device-management-default                 up         10.33.0.51        36101   66487
  sas-viya-fonts-default                             up         10.33.0.51        42297   66533
  sas-viya-geo-enrichment-default                    up         10.33.0.51        39776   66569
  sas-viya-graph-templates-default                   up         10.33.0.51        34078   71240
  sas-viya-jobdefinitions-default                    up         10.33.0.51        44450   71306
  sas-viya-jobexecution-default                      up         10.33.0.51        39764   71339
  sas-viya-links-default                             up         10.33.0.51        43324   71440
  sas-viya-mail-default                              up         10.33.0.51        39950   71422
  sas-viya-maps-default                              up         10.33.0.51        40762   76413
  sas-viya-notifications-default                     up         10.33.0.51        41033   76453
  sas-viya-projects-default                          up         10.33.0.51        46007   76440
  sas-viya-reportalerts-default                      up         10.33.0.51        33950   76518
  sas-viya-report-data-default                       up         10.33.0.51        45349   81584
  sas-viya-reportdistribution-default                up         10.33.0.51        45911   81613
  sas-viya-reportImages-default                      up         10.33.0.51        38184   81610
  sas-viya-report-packages-default                   up         10.33.0.51        38569   81714
  sas-viya-report-renderer-default                   up         10.33.0.51        34013   86715
  sas-viya-reports-default                           up         10.33.0.51        45130   86807
  sas-viya-reporttemplates-default                   up         10.33.0.51        36043   86833
  sas-viya-reporttransforms-default                  up         10.33.0.51        33036   86886
  sas-viya-reportviewernaturallanguageunderstanding-default up         10.33.0.51        45218   92439
  sas-viya-restexecutionprovider-default             up         10.33.0.51        45898   92469
  sas-viya-rowsets-default                           up         10.33.0.51        40687   98397
  sas-viya-sasgraphbuilder-default                   up         10.33.0.51        35529   98435
  sas-viya-scheduler-default                         up         10.33.0.51        37233   98476
  sas-viya-search-default                            up         10.33.0.51        34385   98492
  sas-viya-searchindex-default                       up         10.33.0.51        43335   98572
  sas-viya-templates-default                         up         10.33.0.51        38333   98616
  sas-viya-themes-default                            up         10.33.0.51        46237  104885
  sas-viya-thumbnails-default                        up         10.33.0.51        46465  104916
  sas-viya-transfer-default                          up         10.33.0.51        45469  104985
  sas-viya-web-data-access-default                   up         10.33.0.51        43704  105023
  sas-viya-annotations-default                       up         10.33.0.51        35479  120826
  sas-viya-backup-agent-default                      up         10.33.0.51        45310  120848
  sas-viya-backupmanager-default                     up         10.33.0.51        41403  120962
  sas-viya-compute-default                           up         10.33.0.51        37983  120940
  sas-viya-dataexplorer-default                      up         10.33.0.51        43934  120990
  sas-viya-dataprofiles-default                      up         10.33.0.51        34775  121140
  sas-viya-datastudio-default                        up         10.33.0.51        35066  121188
  sas-viya-drive-default                             up         10.33.0.51        35478  121235
  sas-viya-environmentmanager-default                up         10.33.0.51        39561    5032
  sas-viya-jobexecapp-default                        up         10.33.0.51        40432    5103
  sas-viya-jobflowexecution-default                  up         10.33.0.51        45996    5128
  sas-viya-jobflowscheduling-default                 up         10.33.0.51        37917    5226
  sas-viya-launcher-default                          up         10.33.0.51        36688    5195
  sas-viya-lineage-default                           up         10.33.0.51        42729    5323
  sas-viya-mbagent-default                           up         N/A                 N/A    5008
  sas-viya-modelrepository-default                   up         10.33.0.51        46045    5360
  sas-viya-monitoring-default                        up         10.33.0.51        42061   13121
  sas-viya-naturalLanguageGeneration-default         up         10.33.0.51        43832   13157
  sas-viya-naturalLanguageUnderstanding-default      up         10.33.0.51        45675   22159
  sas-viya-sasthemedesigner-default                  up         10.33.0.51        38505   22172
  sas-viya-sasvisualanalytics-default                up         10.33.0.51        46605   22272
  sas-viya-scoredefinitions-default                  up         10.33.0.51        41441   22340
  sas-viya-scoreexecution-default                    up         10.33.0.51        36636   22369
  sas-viya-studiov-default                           up         10.33.0.51        43194   22451
  sas-viya-tenant-default                            up         10.33.0.51        33325   22513
  sas-viya-themecontent-default                      up         10.33.0.51        38161   22503

sas-services completed in 00:01:14

**Comment by erharb** [comment]
It appears you may have an older version of Viya ARK, try the latest release from here and let us know if the problem persists:

https://github.com/sassoftware/viya-ark/releases

**Comment by svemuri123** [comment]
While reading the documentation for supported ansible versions I saw that its supported only until 2.9
But I see this as the ansible version, do you think that has anything to do with the error?

[buildadmin@AZP-SASVIYA-N00 ~]$ ansible --version
ansible 2.9.9
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/buildadmin/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Sep 26 2019, 13:23:47) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
[buildadmin@AZP-SASVIYA-N00 ~]$

Thanks,
Susmita.

**Comment by erharb** [comment]
Newer versions of it added Ansible 2.9.x support. What is the latest version shown in your downloaded changelog?

https://github.com/sassoftware/viya-ark/blob/master/CHANGELOG.md

**Comment by svemuri123** [comment]
Eric,

I see this, but I am SAS viya 3.4 , did not upgrade to sas viya 3.5 yet.
# Changelog for SAS Viya ARK


## Viya34-ark-1.7 - August 22, 2019

- **Summary**:
    Introducing playbooks to automate tasks required prior to and after performing a SAS Viya upgrade.  Add support for Ansible 2.8.
- Issues addressed:
    - DEPENB-1813 - Ansible 2.8 support in pre-install playbook.
    - DEPENB-1687 - Create pre-upgrade and post-upgrade controller playbooks.
    - DEPENB-1857 - Inventory file hostgroup names now use underscores rather than hyphens (Ansible 2.8).
    - DEPENB-1619 - Provide playbook to assist merging deployment files.
- Ansible Support: Ansible 2.5 - Ansible 2.8


Thanks,
Susmita.

**Comment by kevinlinglesas** [comment]
Hi Sumita,   So being on Viya 3.4, Ansible 2.9.9 is not supported.   Are you attempting to use later/latest Viya ARK running against Viya 3.4 w/ Ansible 2.9.9??

If that is the case, consider downgrading to Ansible 2.8.6 and ensure that you are using a version of Viya ARK released for Viya 3.4.   The Viya34-ark-1.7 version you reference would be ideal.  Note, you will to get that from a 'git clone' of master branch.  Instead you will need to download zip or tar files from the release page (https://github.com/sassoftware/viya-ark/releases/tag/Viya34-ark-1.7)

Another wonderment I had that may or may not be related....  The title of this issue states, "After Linux Rhel patching..."   What is the "patching" reference there mean?

**Comment by svemuri123** [comment]
This issue started happening after the Linux servers where SAS Viya 3.4 resides on were patched (We were RHEL 7.6 now 7.8 after patching), I believe during that Linux upgrade ansible was upgraded too, we were on ansible version 2.6.1 before that.

I will downgrade ansible and see if that resolves the issue.

Thanks,
Susmita.

**Comment by erharb** [comment]
Ok I was thinking that could be the case of using older Viya ARK where newer Ansible not supported.

You should be aware however that newer versions of Viya ARK not only support newer Ansible versions but also still support both Viya 3.4 and Viya 3.5.

**Comment by kevinlinglesas** [comment]
No further response on this issue so closing.
