### ISSUE TITLE
Usage instructions

### ISSUE THREAD

**Issue by AddeGroot** [sassoftware/viya-ark#66]
When i run viya-ark mmsu tools it fails, when running from a "stand-alone" location.

I discovered that i need to place viya-ark inside the sas_viya_playbook.

I missed the instructions for that in the read.me or a separate usage section.
Can this be added?

**Comment by kevinlinglesas** [comment]
In the [MMSU README](https://github.com/sassoftware/viya-ark/blob/master/playbooks/viya-mmsu/README.md) under the **Requirements for Running MMSU Playbooks** section this is mentioned.

- The MMSU playbooks must be placed under the sas_viya_playbook directory where SAS Viya was deployed. The directory structure of this project must be preserved. For example: sas_viya_playbook/viya-ark/playbooks/viya-mmsu/
