### ISSUE TITLE
Error message with deployment Report

### ISSUE THREAD

**Issue by fabricepollet** [sassoftware/viya-ark#67]
Hi 
I received the following error message when I run the deployment report. any ideas??
Tx 
Fabrice

TASK [Check for existing data - ()] *********************************************************************************************************************************************************************
skipping: [ManagementServer]

TASK [Load existing data file] **************************************************************************************************************************************************************************
skipping: [ManagementServer]

TASK [Get SAS host details] *****************************************************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ValueError: could not convert string to float:
fatal: [CASWorker3]: FAILED! => {"changed": false, "module_stderr": "Shared connection to lp30023.posix.covea.priv closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/.sasinst@societe.mma.fr.ansible/ansible-tmp-1600803272.59-87584-55026648244675/AnsiballZ_get_sas_host_details.py\", line 102, in <module>\r\n    _ansiballz_main()\r\n  File \"/tmp/.sasinst@societe.mma.fr.ansible/ansible-tmp-1600803272.59-87584-55026648244675/AnsiballZ_get_sas_host_details.py\", line 94, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/tmp/.sasinst@societe.mma.fr.ansible/ansible-tmp-1600803272.59-87584-55026648244675/AnsiballZ_get_sas_host_details.py\", line 40, in invoke_module\r\n    runpy.run_module(mod_name='ansible.modules.get_sas_host_details', init_globals=None, run_name='__main__', alter_sys=True)\r\n  File \"/usr/lib64/python2.7/runpy.py\", line 176, in run_module\r\n    fname, loader, pkg_name)\r\n  File \"/usr/lib64/python2.7/runpy.py\", line 82, in _run_module_code\r\n    mod_name, mod_fname, mod_loader, pkg_name)\r\n  File \"/usr/lib64/python2.7/runpy.py\", line 72, in _run_code\r\n    exec code in run_globals\r\n  File \"/tmp/ansible_get_sas_host_details_payload_iNalNk/ansible_get_sas_host_details_payload.zip/ansible/modules/get_sas_host_details.py\", line 1791, in <module>\r\n  File \"/tmp/ansible_get_sas_host_details_payload_iNalNk/ansible_get_sas_host_details_payload.zip/ansible/modules/get_sas_host_details.py\", line 1021, in main\r\n  File \"/tmp/ansible_get_sas_host_details_payload_iNalNk/ansible_get_sas_host_details_payload.zip/ansible/modules/get_sas_host_details.py\", line 1260, in _get_sas_root_info\r\nValueError: could not convert string to float: \r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ValueError: could not convert string to float:
fatal: [CASWorker1]: FAILED! => {"changed": false, "module_stderr": "Shared connection to lp30018.posix.covea.priv closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/.sasinst@societe.mma.fr.ansible/ansible-tmp-1600803272.49-87582-45408572528252/AnsiballZ_get_sas_host_details.py\", line 102, in <module>\r\n    _ansiballz_main()\r\n  File \"/tmp/.sasinst@societe.mma.fr.ansible/ansible-tmp-1600803272.49-87582-45408572528252/AnsiballZ_get_sas_host_details.py\", line 94, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/tmp/.sasinst@societe.mma.fr.ansible/ansible-tmp-1600803272.49-87582-45408572528252/AnsiballZ_get_sas_host_details.py\", line 40, in invoke_module\r\n    runpy.run_module(mod_name='ansible.modules.get_sas_host_details', init_globals=None, run_name='__main__', alter_sys=True)\r\n  File \"/usr/lib64/python2.7/runpy.py\", line 176, in run_module\r\n    fname, loader, pkg_name)\r\n  File \"/usr/lib64/python2.7/runpy.py\", line 82, in _run_module_code\r\n    mod_name, mod_fname, mod_loader, pkg_name)\r\n  File \"/usr/lib64/python2.7/runpy.py\", line 72, in _run_code\r\n    exec code in run_globals\r\n  File \"/tmp/ansible_get_sas_host_details_payload_HJqrjI/ansible_get_sas_host_details_payload.zip/ansible/modules/get_sas_host_details.py\", line 1791, in <module>\r\n  File \"/tmp/ansible_get_sas_host_details_payload_HJqrjI/ansible_get_sas_host_details_payload.zip/ansible/modules/get_sas_host_details.py\", line 1021, in main\r\n  File \"/tmp/ansible_get_sas_host_details_payload_HJqrjI/ansible_get_sas_host_details_payload.zip/ansible/modules/get_sas_host_details.py\", line 1260, in _get_sas_root_info\r\nValueError: could not convert string to float: \r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ValueError: could not convert string to float:
fatal: [CASWorker2]: FAILED! => {"changed": false, "module_stderr": "Shared connection to lp30019.posix.covea.priv closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/.sasinst@societe.mma.fr.ansible/ansible-tmp-1600803272.62-87583-82076174589354/AnsiballZ_get_sas_host_details.py\", line 102, in <module>\r\n    _ansiballz_main()\r\n  File \"/tmp/.sasinst@societe.mma.fr.ansible/ansible-tmp-1600803272.62-87583-82076174589354/AnsiballZ_get_sas_host_details.py\", line 94, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/tmp/.sasinst@societe.mma.fr.ansible/ansible-tmp-1600803272.62-87583-82076174589354/AnsiballZ_get_sas_host_details.py\", line 40, in invoke_module\r\n    runpy.run_module(mod_name='ansible.modules.get_sas_host_details', init_globals=None, run_name='__main__', alter_sys=True)\r\n  File \"/usr/lib64/python2.7/runpy.py\", line 176, in run_module\r\n    fname, loader, pkg_name)\r\n  File \"/usr/lib64/python2.7/runpy.py\", line 82, in _run_module_code\r\n    mod_name, mod_fname, mod_loader, pkg_name)\r\n  File \"/usr/lib64/python2.7/runpy.py\", line 72, in _run_code\r\n    exec code in run_globals\r\n  File \"/tmp/ansible_get_sas_host_details_payload_5LvcV3/ansible_get_sas_host_details_payload.zip/ansible/modules/get_sas_host_details.py\", line 1791, in <module>\r\n  File \"/tmp/ansible_get_sas_host_details_payload_5LvcV3/ansible_get_sas_host_details_payload.zip/ansible/modules/get_sas_host_details.py\", line 1021, in main\r\n  File \"/tmp/ansible_get_sas_host_details_payload_5LvcV3/ansible_get_sas_host_details_payload.zip/ansible/modules/get_sas_host_details.py\", line 1260, in _get_sas_root_info\r\nValueError: could not convert string to float: \r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

**Comment by sasjowood** [comment]
Hi @fabricepollet,

If possible, could you provide the results of running the following command on the three hosts mentioned in the error (CASWorker1, CASWorker2, and CASWorker3):

`$ du --summarize /opt/sas`

or using Ansible: 

`$ ansible -i <inventory_file> CASWorker1,CASWorker2,CASWorker3 -a "du --summarize /opt/sas"` 

The provided information does not have to be detailed, `du` should return two columns of output: (1) an integer value, and (2) a path value. If you can confirm these results or explain how they differ, than would be very much appreciated. If possible, please also note the version of du (`$ du --version`) on each machine.

Thanks!

**Comment by kevinlinglesas** [comment]
@fabricepollet are you able to respond to @sasjowood request?

**Comment by kevinlinglesas** [comment]
Closing based on no response.
