### ISSUE TITLE
When using local mirror, pre-install playbook should not check the SAS yum repository

### ISSUE THREAD

**Issue by wweghe** [sassoftware/viya-ark#68]
Hi,

my customer is using a local mirror because their servers are not allowed to connect to the internet.
When running the viya_pre_install_playbook.yml playbook, the playbook fails in the task "Trying to hit the SAS yum repository", which is logical, as the servers are not allowed to connect to the internet.
Problem is that there does not seem to be a "skip-tags" to bypass this test, so I can't run the playbook untill the end.
Would it be possible to either : 
1) check the vars.yml (repository_warehouse) to see whether or not the test is necessary
2) allow a skip-tags to bypass this test

Regards,
Wouter.

**Comment by kevinlinglesas** [comment]
Hi Wouter,
Thank you for the feedback on this customer's scenario.  There is a tag on that task (yum_repo) and you can use that as a skip-tag.    ie, --skip-tags yum_repo
