### ISSUE TITLE
viya_pre_install_playbook.yml fails on clientaliveinterval control even when you run the playbook with the exclude opti

### ISSUE THREAD

**Issue by JMPoilane** [sassoftware/viya-ark#69]
Deployment of Viya 3.5 on Linux CentOS 7. 
ansible-playbook 2.7.12
python version = 2.7.5

Attachment #1 is the playbook's verbose log without the option and fails as expected : 
Your current SSH clientaliveinterval value (420) is smaller than the recommended value of 3600... Either update the value of clientaliveinterval in your SSHD config file, or, if you prefer to suppress this warning, re-run the playbook with a lower threshold by adding -e 'min_ssh_client_alive_internal=1' to the playbook execution command line."

Attachment #2 is the playbook's verbose log with the option and fails with same error as unexpected. **So -e 'min_ssh_client_alive_internal=1' does not work**

Is it normal ? If not cant it be fixed ?

My best regards. 
[nohup.out.erreur-1.zip](https://github.com/sassoftware/viya-ark/files/5355576/nohup.out.erreur-1.zip)
[nohup.out.erreur-2.zip](https://github.com/sassoftware/viya-ark/files/5355577/nohup.out.erreur-2.zip)

**Comment by kevinlinglesas** [comment]
Thank you @JMPoilane for the issue.   We will look closely at it and get back to you.  Can you tell me what version of Ansible you were running?

**Comment by JMPoilane** [comment]
Thank you and sorry I should have filled it :
ansible-playbook 2.7.12
python version = 2.7.5 (default, Apr  2 2020, 13:16:51) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]

De : kevinlinglesas <notifications@github.com>
Envoyé : vendredi 9 octobre 2020 17:04
À : sassoftware/viya-ark <viya-ark@noreply.github.com>
Cc : Jean-Marie Poilane <Jean-Marie.Poilane@sas.com>; Mention <mention@noreply.github.com>
Objet : Re: [sassoftware/viya-ark] viya_pre_install_playbook.yml fails on clientaliveinterval control even when you run the playbook with the exclude opti (#69)


EXTERNAL

Thank you @JMPoilane<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FJMPoilane&data=04%7C01%7Cjean-marie.poilane%40sas.com%7C28fa81f0f5cd4a20da9708d86c648b69%7Cb1c14d5c362545b3a4309552373a0c2f%7C0%7C0%7C637378526836873087%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=tJAJva7gbFot2tvhThcL9gjBeP7ZzOzUs5yggy2klvk%3D&reserved=0> for the issue. We will look closely at it and get back to you. Can you tell me what version of Ansible you were running?

**Comment by JMPoilane** [comment]
Hello, 

Any update on this issue ?

Regards.

Jean-Marie

**Comment by kevinlinglesas** [comment]
Sorry @JMPoilane, not yet.

**Comment by erharb** [comment]
To workaround for now you can modify the value in the main.yml which is used for the rule.

https://github.com/sassoftware/viya-ark/blob/8cd03a3474862b6220947ec1273fc55e0dfbb728/playbooks/pre-install-playbook/roles/viya-ark.preinstall/defaults/main.yml#L67

**Comment by JMPoilane** [comment]
Thank you,

Otherwise can we just modify the option given to the playbook to avoid this control because if I understand well it is not correctly advised in error message ?

Let me explain my proposal :

  1.  Error message says : if you prefer to suppress this warning, re-run the playbook with a lower threshold by adding -e 'min_ssh_client_alive_internal=1'
  2.  Instead can we run the playbook with option : -e ‘min_clientaliveinterval=1’ ?


De : Eric Harbeston <notifications@github.com>
Envoyé : lundi 19 octobre 2020 15:03
À : sassoftware/viya-ark <viya-ark@noreply.github.com>
Cc : Jean-Marie Poilane <Jean-Marie.Poilane@sas.com>; Mention <mention@noreply.github.com>
Objet : Re: [sassoftware/viya-ark] viya_pre_install_playbook.yml fails on clientaliveinterval control even when you run the playbook with the exclude opti (#69)


EXTERNAL

To workaround for now you can modify the value in the main.yml which is used for the rule.

https://github.com/sassoftware/viya-ark/blob/8cd03a3474862b6220947ec1273fc55e0dfbb728/playbooks/pre-install-playbook/roles/viya-ark.preinstall/defaults/main.yml#L67<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fsassoftware%2Fviya-ark%2Fblob%2F8cd03a3474862b6220947ec1273fc55e0dfbb728%2Fplaybooks%2Fpre-install-playbook%2Froles%2Fviya-ark.preinstall%2Fdefaults%2Fmain.yml%23L67&data=04%7C01%7Cjean-marie.poilane%40sas.com%7C5f4af7bbf52742eb0e8508d8742f409b%7Cb1c14d5c362545b3a4309552373a0c2f%7C0%7C0%7C637387093578104993%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=KkWf57Fay%2B57tNt9lhu%2F4spWLqB4fkPsFmB4vX0rcRA%3D&reserved=0>

**Comment by JMPoilane** [comment]
Hello again,

a) I could make it work. You simply need to specify in playbook this correct argument : 
-e 'min_clientaliveinterval_val=1'

b) Therefore it means that error message received with proposed workaround is wrong see : 
... re-run the playbook with a lower threshold by adding -e 'min_ssh_client_alive_internal=1'  

c) So instead of changing the value in main.yml it could be more logical to change the error message. Do you agree ? That would be : 
... re-run the playbook with a lower threshold by adding **-e 'min_clientaliveinterval_val=1'**

**Comment by kevinlinglesas** [comment]
Hi Steve,

Yes, the error message needs to be changed.   Thank you for helping us to identify this oversight.    We will make the change in a future release.

**Comment by kevinlinglesas** [comment]
Fixed by [Viya35-ark-1.12](https://github.com/sassoftware/viya-ark/releases/tag/Viya35-ark-1.12)
