### ISSUE TITLE
How to bypass the sas_yum_urls when we have a local viya mirror?

### ISSUE THREAD

**Issue by stagba** [sassoftware/viya-ark#70]
I am trying to run the precheck and fails on "Trying to hit the SAS yum repositories"  that are listed in the main.yml.   I already have a local repo and need to know what files need to be modified to acknowledge the local repo.  I already have it defined in the inventory.ini of the sas viya playbook.  Please advise.  Thanks in advance.

Here is the entry on your main.yml

##
##
##
sas_yum_urls:
  - ses.sas.download
  - bwp1.ses.sas.download
  - bwp2.ses.sas.download
  - sesbw.sas.download

**Comment by kevinlinglesas** [comment]
You can skip the check by using `--skip-tags yum_repo`.    Or you can change the list of values for `sas_yum_urls` to reflect your local repo host(s).

**Comment by stagba** [comment]
Kevin,
The skip-tags worked.   But if I were to try and define the local sas_repo in the main.yml, what would the syntax would be like?  I think there would be more changes since the pre.network_and_bandwitdth_check.yml has the shell: "curl -v k htps://{{item}}/"     <-- which would not sync with a local file:/// location like I defined in the actual sas_playbook's vars.yml.     
   
sas_yum_urls:
   - file:///sasviya/sas_repo/        <--- this is what I have in my vars.yml

thanks!
Steve

**Comment by kevinlinglesas** [comment]
I misunderstood when you said "local repo".   I didn't realize it was a file.   I thought the repo was on another locally available host.      The check of 'sas_yum_urls' is currently implemented to expect a list of hosts.   

Is using skip-tags sufficient for you?    Addressing repo as a local filesystem is not something we support and this time.

**Comment by stagba** [comment]
Yes the skip-tag is sufficient.  The local repo is on a shared file system local to the servers, in this case, the service-layer, which I am installing from due to no access outside the firewall.
