### ISSUE TITLE
Viya-ARKCD - Namespace Admin Permissions: Insufficient

### ISSUE THREAD

**Issue by ken-sys** [sassoftware/viya-ark#71]
Hi,

I got a single issue noted when running Viya-ARKCD on Oct 28:

> Sample requests Error occured | HTTPConnectionPool(host='server.demo.sas.com', port=443): Max retries exceeded with url: /hello-world (Caused by NewConnectionError(': Failed to establish a new connection: [Errno 111] Connection refused',))

Would you have an idea what I can do about this issue?
Thanks!

**Comment by lasiva** [comment]
Hi Ken:

I'd like a little more information about your cluster.  Is this Azure with nginx ingress controller and a Load Balancer?  We support only Azure and nginx for the November GA.  I'm going to add some documentation on how to determine the Ingress Host and Port.  I think that is causing the hello app test to fail.

Latha Sivakumar

**Comment by ken-sys** [comment]
Latha, thanks for the assist.
Yes, this is a non-standard environment with K3S from rancher on an internal system.

It looks like I missed the step to create an ingress. 
I'm working on that now to get nginx going.
I'll retest and report back.  Thanks!

**Comment by lasiva** [comment]
@ken-sys I'm closing this issue since I have not heard back from you.  Please feel free to re-open the issue if you have not resolved it.  Thanks!

**Comment by kevinlinglesas** [comment]
Also,  this issue appears to be a [viya4-ark](https://github.com/sassoftware/viya4-ark) issue not a [viya-ark](https://github.com/sassoftware/viya-ark) issue.   It doesn't belong here.

**Comment by kevinlinglesas** [comment]
Closing.   If needed re-open against viya4-ark project.
