### ISSUE TITLE
pre-install-playbook - The directory /opt/sas only has 777 permissions. It should have at least 755. Edit the storage_list variable if this is a mistake. Or add --skip-tags skipstoragefail to bypass.

### ISSUE THREAD

**Issue by bheinsius** [sassoftware/viya-ark#72]
I have /opt/sas as a symlink like this:

```
[sasinst@sasviya352 working]$ ls -l /opt/sas
lrwxrwxrwx. 1 root root 21 Oct 30 17:01 /opt/sas -> /home/sasinst/opt/sas
[sasinst@sasviya352 working]$
```

/home/sasinst/opt/sas is:

```
[sasinst@sasviya352 working]$ ls -ld /home/sasinst/opt/sas
drwxr-xr-x. 3 sasinst sasinst 26 Oct 30 17:01 /home/sasinst/opt/sas
[sasinst@sasviya352 working]$
```

the pre-install playbook fails with:

`The directory /opt/sas only has 777 permissions.\nIt should have at least 755.\nEdit the storage_list variable if this is a mistake.\nOr add --skip-tags skipstoragefail to bypass.\n`

That doesn't seem right.

**Comment by kevinlinglesas** [comment]
Hi Bart,
That fail msg doesn't make much sense, does it?    Possibly something about how the symlink is handled by ansible.  I will check.    

When you opened this Issue did you see/use the Bug Report template?   Can you provide the following info?
**Environment**
- [ ] Ansible version:
- [ ] Python version:
- [ ] OS version: 
- [ ] Failed playbook tasks log (or entire playbook log) [Attach]
- [ ] What version of Viya 3.x is being deployed?
- [ ] What version of Viya ARK?

**Comment by bheinsius** [comment]
**Environment**
- [ ] Ansible version:
ansible 2.9.14

- [ ] Python version:
python version = 2.7.5

- [ ] OS version: 
CentOS Linux release 7.8.2003 (Core)

- [ ] Failed playbook tasks log (or entire playbook log) [Attach]
[viya_pre_install_playbook.log](https://github.com/sassoftware/viya-ark/files/5478348/viya_pre_install_playbook.log)

- [ ] What version of Viya 3.x is being deployed?
3.5

**Comment by screnshaw** [comment]
Hi Bart,
In this case, you would need to modify the defaults in the main.yml file to reflect the custom Viya root path to which you are installing.  You have set /opt/sas as a symlink and the actual installation location is /home/sasinst/opt/sas.  In the main.yml defaults file you would edit the storage_list variable and change the /opt and /opt/sas paths to reflect the respective paths under /home/sasinst. This way the pre-install playbook would be checking the true installation location of the SAS Viya files.
No code changes are needed for this issue. I am closing.
