### ISSUE TITLE
error on allowed languages for server

### ISSUE THREAD

**Issue by devopsasadm** [sassoftware/viya-ark#73]
Hi,

We are running Viya Ark on a SUSE 12 server and it is coming back with an error regarding language locale.  When we check the versions of language, the language is in the approved list however we also have UTF-8 specified.  Is there something we need to indicate differently?
![locale1](https://user-images.githubusercontent.com/50176402/99296117-3fd03a00-2814-11eb-84bd-47d3b349d7a3.PNG)
![locale2](https://user-images.githubusercontent.com/50176402/99296118-3fd03a00-2814-11eb-81fd-c070bd447256.PNG)

See attached screen shots.

- [ ] Ansible version: 2.9
- [ ] Python version: 3.4
- [ ] OS version: SUSE 12
- [ ] What version of Viya 3.x is being deployed? 3.5

**Comment by kevinlinglesas** [comment]
We will need to try and reproduce.   Is this SLES 12.2 or 12.3?    We do not support 12.5 or any other versions.
I see that the `Current LANG:` task just above showed blank, so there must be something wrong with the underlying command used to gather information.

Any chance of getting the entire log with -vvvv verbosity?

**Comment by AlissaSchleich** [comment]
June,  Did you resolve this issue?   Can you please let us know if you can get the log with the -vvvv verbosity and what SLES 12 version you are running.

**Comment by kevinlinglesas** [comment]
Someone else has reproduced this issue with SUSE 12.2, so we will be keeping this issue open.

**Comment by kevinlinglesas** [comment]
Reproducing this issue has been illusive.   When checking with someone who we had heard had reproduced it, the test env was no longer available and it has not been reproduced.    Therefore, I am closing this issue.    Please reopen if there is any re-occurrence.
