### ISSUE TITLE
playbooks/viya-mmsu/viya-services-stop.yml  dont work when a worker est down

### ISSUE THREAD

**Issue by framhc** [sassoftware/viya-ark#74]
**Describe the bug**
A clear and concise description of what the issue is.

**Environment**
- [ ] Ansible version:
- [ ] Python version:
- [ ] OS version: 
- [x] Failed playbook tasks log (or entire playbook log) [Attach]
- [ ] What version of Viya 3.x is being deployed?

**To Reproduce**
1. Firstly, ...
2. Then, ...
3. 

**Expected behavior**

When a worker is down (shutdown ), playbook can't ssh this Worker. Then playbooks/viya-mmsu/viya-services-stop.yml  stop at the ssh error.
A workaround is to delete the ligne refrencing this worker on the inventory.ini. 
But the customer ask us to resolve the issue on playbooks/viya-mmsu/viya-services-stop.yml 

Thank you 

$ ansible-playbook viya-ark-master/playbooks/viya-mmsu/viya-services-stop.yml -e "enable_stray_cleanup=true"
 
PLAY [localhost] **************************************************************************************************************************************************************************************************************
 
TASK [Gathering Facts] ********************************************************************************************************************************************************************************************************
ok: [localhost]
 
PLAY [sas_all] ****************************************************************************************************************************************************************************************************************
 
TASK [Check any SAS process running] ******************************************************************************************************************************************************************************************
fatal: [worker3]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: ssh: connect to host viya-worker3 port 22: Connection refused", "unreachable": true}
ok: [deployTarget]
ok: [controller]
ok: [worker2]
ok: [worker4]
ok: [worker1]
 
NO MORE HOSTS LEFT ************************************************************************************************************************************************************************************************************
 
PLAY RECAP ********************************************************************************************************************************************************************************************************************
controller                 : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
deployTarget               : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
localhost                  : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
worker1                    : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
worker2                    : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
worker3                    : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0
worker4                    : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0

**Comment by erharb** [comment]
This is on purpose, the viya-mmsu playbooks expect all involved hosts to be reachable by Ansible. If you explicitly want to omit a host from being considered by viya-mmsu then you will need to provide it an inventory file without that host mapped.

**Comment by kevinlinglesas** [comment]
Closing based on @erharb response above.
