### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 15: ordinal not in range(128)

### ISSUE THREAD

**Issue by lardabi** [sassoftware/viya-ark#75]
**Describe the bug**
Running the viya-ark playbook viya-deployment-report.yml causes an Unicode Error on task Get SAS host details.

The command:

ansible-playbook /home/viyadep/viya-ark-master/playbooks/deployment-report/viya-deployment-report.yml -i /home/viyadep/sas_viya_playbook/inventory.ini -vvv

inventory.ini is the inventory used for install.

The output (simplified):
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 15: ordinal not in range(128)

**Environment**
- [x] Ansible version: ansible 2.10.3
- [x] Python version:  python version = 2.7.5 (default, Aug 13 2020, 02:51:10) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
- [x] OS version: RHEL 7.9 (Maipo)
- [x] Failed playbook tasks log (or entire playbook log) [Attach] Task "Get SAS host details" Attached full log
[ansible_log.txt](https://github.com/sassoftware/viya-ark/files/5701767/ansible_log.txt)

- [x] What version of Viya 3.x is being deployed? 3.5

**To Reproduce**
1. Run command to generate deployment report on already installed environment:
ansible-playbook /home/viyadep/viya-ark-master/playbooks/deployment-report/viya-deployment-report.yml -i /home/viyadep/sas_viya_playbook/inventory.ini -vvv

**Expected behavior**
No errors, and the deployment report is generated.

**Comment by kevinlinglesas** [comment]
@lardabi thank you for submitting this issue.     Assigning this issue to @sasjowood for further investigation.

**Comment by kevinlinglesas** [comment]
Having some issue assigning the issue to @sasjowood.  Have contacted him via email regarding this issue.

**Comment by erharb** [comment]
@kevinlinglesas Josh needed to be added as a member of the project, which I just now did so I could assign him

**Comment by kevinlinglesas** [comment]
Fixed by [Viya35-ark-1.12](https://github.com/sassoftware/viya-ark/releases/tag/Viya35-ark-1.12)
