### ISSUE TITLE
Viya 3.5 Pre-Install failed while running pre_install_playbook.yml

### ISSUE THREAD

**Issue by mukeshkham** [sassoftware/viya-ark#77]
**Describe the bug**
I’m trying to run the sasviya_ark_preinstall check, the check seems to run fine except for below issue.

I’m wondering if there is any update/edit required on viya_ark_master/playbooks/pre-install-playbook/roles/viya-ark.preinstall/tasks/pre.os_version_check.yml   file

Please note I’m running this check using Ansible Tower.

**Environment**
- [ ] Ansible version:  Tower 3.5.2   , Ansible 2.6.19
- [ ] Python version: Python 2.7.5
- [ ] OS version: RHELv7.9
- [ ] Failed playbook tasks log (or entire playbook log) [Attach]

TASK [viya-ark.preinstall : Ensure that the Operating System is supported for Viya] ***
10:42:56
81
fatal: [core3]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'ansible_os_family' is undefined\n\nThe error appears to have been in '/var/lib/awx/projects/_29706__qa_sasviya_ark_preinstall_check/repos/viya_ark_master/playbooks/pre-install-playbook/roles/viya-ark.preinstall/tasks/pre.os_version_check.yml': line 18, column 5, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n- block:\n - name: Ensure that the Operating System is supported for Viya\n ^ here\n"}

- [ ] What version of Viya 3.x is being deployed? 3.5

**To Reproduce**
1. Firstly, ...
2. Then, ...
3. 

**Expected behavior**
Preinstall_Check to run without any failures.

**Comment by kevinlinglesas** [comment]
What release of viya-ark are you using?    

Please answer the bug report template:
**Environment**
- [ ] Ansible version:
- [ ] Python version:
- [ ] OS version: 
- [ ] Failed playbook tasks log (or entire playbook log) [Attach]
- [ ] What version of Viya 3.x is being deployed?

**Comment by erharb** [comment]
Ansible Tower is not supported by SAS for use with Viya 3.x, and also is not supported for use with Viya ARK.

**Comment by mukeshkham** [comment]
> What release of viya-ark are you using?  Viya35-ark-1.11 
> 
> Please answer the bug report template:
> **Environment**
> 
 Ansible version: Tower 3.5.2 , Ansible 2.6.19
 Python version: Python 2.7.5
 OS version: RHELv7.9
 Failed playbook tasks log (or entire playbook log) [Attach]
TASK [viya-ark.preinstall : Ensure that the Operating System is supported for Viya] ***
10:42:56
81
fatal: [core3]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'ansible_os_family' is undefined\n\nThe error appears to have been in '/var/lib/awx/projects/_29706__qa_sasviya_ark_preinstall_check/repos/viya_ark_master/playbooks/pre-install-playbook/roles/viya-ark.preinstall/tasks/pre.os_version_check.yml': line 18, column 5, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n- block:\n - name: Ensure that the Operating System is supported for Viya\n ^ here\n"}

 What version of Viya 3.x is being deployed? 3.5

**Comment by mukeshkham** [comment]
I have been informed to add "gather_facts: true" by our Ansible Tower  Administrator to help resolve this issue, can you please advise which script I need to add it.

**Comment by erharb** [comment]
Sorry but since Ansible is not supported we do not have the experience with it needed to guide you on this. My recommendation might be to having Ansible installed on a separate smaller node or on a designated control node in the Viya deployment and then have Tower execute ansible remotely on that node to run Viya ARK and the Viya deployment operations.
