### ISSUE TITLE
Review microservice dependencies for VI/AML/CDD

### ISSUE THREAD

**Issue by iagomez** [sassoftware/viya-ark#78]
**Is your feature request related to a problem? Please describe.**
We have an AML CDD 8.2 deployment on Viya 3.5. The architecture includes separate servers for Elasticsearch and Viya microservices.
The current startup order executes the all services script on the microservices box **before** elasticsearch:
```
82554 2021-03-10 12:25:52,533 p=1747 u=ec2-user n=ansible | TASK [Start SAS all services which might take a while] *************************
82555 2021-03-10 12:27:26,879 p=1747 u=ec2-user n=ansible | changed: [cas-controller]
82556 2021-03-10 13:03:55,660 p=1747 u=ec2-user n=ansible | changed: [deployTarget]
82557 2021-03-10 13:03:55,667 p=1747 u=ec2-user n=ansible | PLAY [sas_all:!consul:!rabbitmq:!httpproxy:!pgpoolc:!sasdatasvrc:!sas_casserver_primary] ***
82558 2021-03-10 13:03:55,677 p=1747 u=ec2-user n=ansible | TASK [Check SAS svas command existence] ****************************************
82559 2021-03-10 13:03:56,120 p=1747 u=ec2-user n=ansible | ok: [spre]
82560 2021-03-10 13:03:56,178 p=1747 u=ec2-user n=ansible | ok: [elastic]
82561 2021-03-10 13:03:56,183 p=1747 u=ec2-user n=ansible | TASK [Start SAS all services which might take a while] *************************
82562 2021-03-10 13:05:12,862 p=1747 u=ec2-user n=ansible | changed: [elastic]
82563 2021-03-10 13:05:45,562 p=1747 u=ec2-user n=ansible | changed: [spre]
```

**Elasticsearch service**
![image](https://user-images.githubusercontent.com/2080150/110678649-8b806800-81a4-11eb-85f0-6aa30d13e9d6.png)

**svi-datahub service**
![image](https://user-images.githubusercontent.com/2080150/110678705-9cc97480-81a4-11eb-947b-58c58e8aab9d.png)

The `svi-datahub` service has a hard dependency on `Elasticsearch` and the microservice log gets flooded with error messages until elasticsearch starts. This propagates to other `svi-*` services that cannot start until `svi-datahub` is healthy.
![image](https://user-images.githubusercontent.com/2080150/110677796-91297e00-81a3-11eb-9ed4-5bc2167c9f03.png)

To be clear this is **not** a critical issue since all the `svi-*` do eventually come up as "ready" but it takes a while for things to stabilize and the logs are flooded with `ERRORS`.

**Describe the solution you'd like**
Start elasticserach services before all microservices.

**Additional context**
Let me know if you need any other details from me.

**Comment by iagomez** [comment]
Thank you for adding the label here @kevinlinglesas.

Thought I'd stop by to see if this is something you guys are considering to implement.

Thanks!

**Comment by kevinlinglesas** [comment]
@iagomez, apologies for long neglect in responding to this issue.   The viya-ark project has been in a mode of support/maintenance but not actively working on enhancements for some time now.    This particular enhancement would also not likely be something within the scope of the [MMS](https://github.com/sassoftware/viya-ark/blob/master/playbooks/viya-mmsu) tool.  Therefore, I am closing this issue.   Thank you again for your enhancement requst.
