### ISSUE TITLE
Viya -ark mmsu encountering an error when trying to run as SUDO

### ISSUE THREAD

**Issue by billwisotsky** [sassoftware/viya-ark#79]
**Describe the bug**
A clear and concise description of what the issue is.

**Environment**
- [ ] Ansible version: 2.8.4
- [ ] Python version: 2.7.5
- [ ] OS version: RH Linux 6
- [ ] Failed playbook tasks log (or entire playbook log) -- MMSU Start Server Playbook
[log_20210312.txt](https://github.com/sassoftware/viya-ark/files/6141702/log_20210312.txt)
[log_20210312.txt](https://github.com/sassoftware/viya-ark/files/6141704/log_20210312.txt)

- [ ] What version of Viya 3.x is being deployed? Viya 3.5

**To Reproduce**
Trying to run the mmsu playbooks. Able to run the start services and status playbooks using the deployment account and it works fine. Not able to run the start service playbook since services need to be started as root.

They have tried to run the playbook using
sudo ansible-playbook ./viya-services-status.yml -i ../../../inventory.ini

and then get the attached log. I turned on verbose logging so you would have more information. 

**Expected behavior**
Expected behavior is that whey they run 
sudo ansible-playbook ./viya-services-status.yml -i ../../../inventory.ini
they get prompted for the SUDO users password and the playbook runs without error.

**Comment by erharb** [comment]
This is not a Viya ARK issue but rather an environment related one. You'll need to setup the environment and Ansible properly for connections. You do not run ansible-playbook using sudo, but rather need sudo access from the users logging in to the remote machines, and there are various ways you can setup ansible to do this:

https://docs.ansible.com/ansible/latest/user_guide/become.html#become-command-line-options
