### ISSUE TITLE
Deployment Report: ValueError: could not convert string to float

### ISSUE THREAD

**Issue by alan-demarq** [sassoftware/viya-ark#8]
This task doesn't work on all hosts:

TASK [Get SAS host details] *****************************************************************************************************************************************************************
ok: [cw2]
ok: [cw1]
ok: [cc1]
fatal: [pr1]: 
FAILED! => 
{"changed": false, 
"module_stderr": "Shared connection to cap-dp-pr-001.example.co.uk closed.\r\n", 
"module_stdout": "Traceback (most recent call last):\r\n  
    File \"/tmp/ansible_j6VFeJ/ansible_module_get_sas_host_details.py\", line 1708, in <module>\r\n
    main()\r\n
   File \"/tmp/ansible_j6VFeJ/ansible_module_get_sas_host_details.py\", line 961, in main\r\n
    packages, available_update_count = _get_sas_package_info(module, package_manager, include_package_files)\r\n
  File \"/tmp/ansible_j6VFeJ/ansible_module_get_sas_host_details.py\", line 1380, in _get_sas_package_info\r\n
    results = _get_installed_package_info(module, include_installed_files)\r\n
  File \"/tmp/ansible_j6VFeJ/ansible_module_get_sas_host_details.py\", line 1471, in _get_installed_package_info\r\n
    value = _bytesHumanReadable(value)\r\n
  File \"/tmp/ansible_j6VFeJ/ansible_module_get_sas_host_details.py\", line 1678, in _bytesHumanReadable\r\n
    num_bytes = float(num_bytes)\r\nValueError: could not convert string to float: (none)\r\n",
 "msg": "MODULE FAILURE", "rc": 0}
ok: [cw3]
ok: [is1]
ok: [cw4]
ok: [ms1]

**Comment by erharb** [comment]
This has been fixed and merged in the internal gitlab and will make the next promotion to github

https://gitlab.sas.com/sassoftware/viya-ark/merge_requests/32
https://rndjira.sas.com/browse/DEPENB-1689
