### ISSUE TITLE
Remove the pre.timeouts_config

### ISSUE THREAD

**Issue by aekuback** [sassoftware/viya-ark#80]
**Describe the bug**
Changing the Default Timeout is no longer needed in Viya.  See the defect here:  http://sww.sas.com/ds/DefectsSearch/S1570/S1570824.html

**Environment**
All Viya-ark releases

**To Reproduce**
NA

**Expected behavior**
Just remove all references to this task as it is no longer needed.

**Comment by kevinlinglesas** [comment]
Thank you @aekuback for opening this issue.   We will read through the referenced defect and determine what changes are needed.

**Comment by kevinlinglesas** [comment]
systemd DefaultTimeout parameters are removed as of release [Viya35-ark-1.14](https://github.com/sassoftware/viya-ark/releases/tag/Viya35-ark-1.14).
