### ISSUE TITLE
Automatically install RHEL 8 compatibility packages

### ISSUE THREAD

**Issue by AWSmith0216** [sassoftware/viya-ark#82]
**Is your feature request related to a problem? Please describe.**
Not a problem exactly, but the Viya ARK handles installing 'required' packages, as well as the 'nice-to-have' ones. However, for RHEL 8 there are several packages classified as compatibility packages. For some reason, rather than installing these automatically, it checks to see if they are installed, and if not, fails with an error telling you they aren't installed. Refer to:
https://github.com/sassoftware/viya-ark/blob/7b851591660dca29329e748fda72374b8a0a79e2/playbooks/pre-install-playbook/roles/viya-ark.preinstall/tasks/pre.required_packages_config.yml#L55-L62

**Describe the solution you'd like**
Automatically install the compatibility packages

**Describe alternatives you've considered**
This is easy enough to work around, but it doesn't seem logical to install the other packages and not install these

**Comment by kevinlinglesas** [comment]
@AWSmith0216 we do have plans to automatically install these compatibility packages.    The release where this was planned is not yet determined based on resources.   I will add this issue to our SAS internal JIRA story tracking the enhancement.

**Comment by kevinlinglesas** [comment]
The RHEL 8 compatibility packages are addressed by release [Viya35-ark-1.14](https://github.com/sassoftware/viya-ark/releases/tag/Viya35-ark-1.14)
