### ISSUE TITLE
sesudo instead sudo (eTrust)

### ISSUE THREAD

**Issue by framhc** [sassoftware/viya-ark#87]
Hi all

My customer is on linux 7.8. instead sudo, the system is controlled via eTrust, and is configured to use sesudo ( /opt/SEOS/bin). He ask us if viya-ark support this binary.

Do we support this configuration?

PS: I see in the documenation that we can use the option become-method.

Thanks in advance

**Environment**
- [ ] Ansible version: 2.8
- [ ] Python version:
- [ ] OS version: Linux Redhat 7.8
- [ ] Failed playbook tasks log (or entire playbook log) [Attach]
- [ ] What version of Viya 3.x is being deployed?

**To Reproduce**
1. Firstly, ...
2. Then, ...
3. 

**Expected behavior**

**Comment by erharb** [comment]
Here's the ansible documentation where it appears you can configure the become executable command and any other options it may require when it differs from sudo:
https://docs.ansible.com/ansible/latest/collections/ansible/builtin/sudo_become.html
