### ISSUE TITLE
Required sudo permissions for viyadep

### ISSUE THREAD

**Issue by LuciaSantin** [sassoftware/viya-ark#88]
Hi experts,

our customer wants to limit as much as possible after the installation the permissions for the user viyadep so that he can only start and stop the environment. I have proposed to create a new line allowing only the services management, for example :

viyadep ALL=(root,sas) /etc/init.d/sas-viya-*

But my doubt is, does the viya ark start and stop script need any additional permissions for viyadep? bin/sh or passwordless ssh between the machines?

Many thanks
regards
Lucía

**Comment by erharb** [comment]
All service start/stop calls can be found in the [viya-svs.sh script](https://github.com/sassoftware/viya-ark/blob/master/playbooks/viya-mmsu/viya-svs.sh)

**Comment by LuciaSantin** [comment]
Hi erharb,

Thanks for your message. 

So it's not clear to me what kind of permissions are needed for this. I have tested adding viyadep ALL=(root,sas) /etc/init.d/sas-viya-* in sudoers file and in that case scripts in /etc/init.d/sas-viya-* work properly.

But I supposed viya-ark scripts need some kind of additional permissions. Do we have this information about user viyadep? Which are the minimum explicit requirements of the user in order to be able to execute the start/stop scripts?

Many thanks in advanced
Regards
Lucía

**Comment by erharb** [comment]
the viya-mmsu playbook and scripts appear to run as root, at some point in the script you can see it runs su as user sas as well. It doesn't care about any user beyond those.

**Comment by LuciaSantin** [comment]
Hi Eric, many thanks for your help.
