### ISSUE TITLE
Fatal TASK [Perform host connection checks] 

### ISSUE THREAD

**Issue by KaminoU** [sassoftware/viya-ark#89]
Hello

I face a weird issue and have no clue at all.

It appears during the viya_pre_install_playbook.yml running.
In my inventory, I also specify the ansible_ssh_private_key_file propertie.

the playbook raise one detailed error in the block named TASK [Perform host connection checks], then after a while, it raises again a synthesis error in the block named TASK [Identify any pre-flight check failures]

For each node the errors appear 2 times (with differents IP)

- SSH Passwordless is configured from the Ansible to the differents nodes
- /etc/hosts and inventory.ini are also correctly configured

Do you have an idea please ?

**Environment**
- Ansible version: 2.9.15
- Python version: 2.7.5
- OS version: RedHat 7.6
- Viya 3.5
- Failed playbook tasks log

  264 2022-02-16 09:43:10,564 p=142158 u=viya n=ansible | TASK [Perform host connection checks]**************************************************************************************************************************************

  265 2022-02-16 09:43:11,639 p=142158 u=viya n=ansible | fatal: [worker1]: FAILED! => {"changed": false, "host_keys": {"10.236.209.18": "AAAAB3NzaC1yc2EAAAADAQABAAABAQC8iW/j/N86XP70+mgOxbmD9TKgFN6DDNly5M0c0Zz0+FGgO2oi/TCDwUexI4vFAiQ+ ggCfYcs3+kdg9LTj4Ydz2VQS6+SpxeWZfAndANkB+9rrCcXSper9UZ8ZsczndrO2E3l6FIbSK4UjpR8bsAwzs0c29PBcK7C33Ywl9+KPCe62ddlwU1jyg6kj9R6Gjq1GWUNjoNhe1SJBtja+FdC37QE7kLe9u6srj7dulVcLkst08b8jbOJGqL9MWc2uiQuAix2tAQ1yRdMRXOGARuJ1UoNCzdci3n/qfZUcQ4d SHswEX18QJj5zd29jFLR0isKiRVUu1dQgadEunNx1YWc9", "10.236.209.20": "AAAAB3NzaC1yc2EAAAADAQABAAABAQDZNNQwnqOK16c0oWMyTl1teITBGCTn5SPYvXvhlBWety59KaoGKbkf4DA5k6XTdfv4SiGVn8yzGfxgovsF0RfTM6m9da1IPGun6+QWijNRC/EX0fr2Gxx9ONktHk5tzXL7rucCJ AOxKCdcHuGpKJW9NICesd6KhiDl+9Nlx463wZsgFY1K/N4PfNDI+nyYCQbAXdydbmRSoXLS5va4+Ktc7L4qnMif4h2nsk2vZp5b6CBCfJOqTmB58n2tI4gI8wkrEGfP2ol4CSMbQnHyu7V24EMvflGgSGGexuQtbuG9Cr8yenkCPZVytbUNq7uX6NGVazK+OPH2q5k5fPWJC4Ix", "10.236.209.21": "AAA AB3NzaC1yc2EAAAADAQABAAABAQDHdsF42uUsp8Djvzm/sLy4aMlYuXqZLUVKwakOOxfrA+6nyRxUp8vJowZTn0vES5omxKdpaOXe29jp4ZdrD8FCfjHHX6QBv098mnC0lV6gQus6wQwz2Yaded5kiMlH6uvg2HSepYhMMA1xNGqyTdM9a/o2IPfCcE67o0Ep4ShfdYvVyG1bB28Sr5ibrvozeyD2JLlBnYPT+i PIBQBoamy5D2SQMR9KJCynhEKCjv01dDrDOxDLpT8jYLmeI2qSNs3QX0V1/mxeDqRahBXZm11OxXUgpy7eFDLWh7VK4Q90nko9AsrWwwpv1fxYPEGJPQPcn9/i4ndv6+NT9TevLTSr", "10.236.209.22": "AAAAB3NzaC1yc2EAAAADAQABAAABAQDJPwL45/nGAsbtvUE1On6ar5DfXD5GsBB4dm/dK2D3 KOc70sl/alPS1zz7+LQgu88yyhVfJkZVom8QpFfVqP22k0BbLvi/ua/xGC6pU+am+npodtPBB97c7jx+lpnhd+icJf//GfrK+azX0lcqOycVFmdaUzwPikhNwW+8KUElDgDi41rPF4+N9ze+vn8mTn6UGif2LAZ4ZJS7ocZsU3FUP8lJy01y3UZ3ach/VvdIo1G5NNuOx52QQzAaxA4E+7OZge3KsCFaCYNkd9E LGDZ0iPUKBncnexmkOnI6xK6vOtH4Yp8h8M5tfcZ43WkRIIpv+vCcTN92TVhCn3MgU+QT", "10.236.209.23": "AAAAB3NzaC1yc2EAAAADAQABAAABAQDMtIPPEeIo/OyLXu2z6vFw98sckXEQFzDGEmqSMlQBXXwQP5SDvU9McYm5eA58yXAvcgkWenoYQxF9YwmJrKFvW2YX9r4xXp5sRjcdTRJpMZ0yr wzIE0VtUNA4E8v/3PMVUp4mG3ZZfvZTsRsMGMSSxX597r+SWdSJWlNTzWZrUPeqjPc9XM04v4Vz040SztdLKDzphIYi7unz3E524mwz3vpVaIGTgYQYPwqtk0aZxpBYHyxYz5idE8lpFpYc8jKH+GIXhh6/kvQoGatMEzoYzEPrJEn/IrPILZZySLeSa5tJwJQp7rodMNBzioDd16O3NBMys4YudmDbW/rD067J ", "n0999pv.res.private": "AAAAB3NzaC1yc2EAAAADAQABAAABAQCvZmFsVcUiifHO486psUy5TPRUTYnUKD79x4mEmVD1VpFJaj2xRBtYWrcAcbB4FGfuB2TLm3wBW+VNvZ9Z+RA2sLN47MC3LNDyoSmD/EZriYWeNSdLLW8h3eQoM9D+VEO5nn/q7/jRjjfoPJQKaa+9ztxuTvNy4AkToJqI/FFMf piWXmG7+tJK1HRMJm+HeJuvKDP/OPyaclydOMaf9WpO235v9D8MPwlFVyF9i/s0n21Ah/gGLlHdWEkJ5Auwx07oYGfJFhkTwxaCy26hgt11ULb5fUyDDudahCJZ5rjBQxL98ugY3puOoUjfTLGpPiP0ayxEmMYvMZLwfsUr0HvJ", "n1003pv.res.private": "AAAAB3NzaC1yc2EAAAADAQABAAABAQ DHdsF42uUsp8Djvzm/sLy4aMlYuXqZLUVKwakOOxfrA+6nyRxUp8vJowZTn0vES5omxKdpaOXe29jp4ZdrD8FCfjHHX6QBv098mnC0lV6gQus6wQwz2Yaded5kiMlH6uvg2HSepYhMMA1xNGqyTdM9a/o2IPfCcE67o0Ep4ShfdYvVyG1bB28Sr5ibrvozeyD2JLlBnYPT+iPIBQBoamy5D2SQMR9KJCynhEKCj v01dDrDOxDLpT8jYLmeI2qSNs3QX0V1/mxeDqRahBXZm11OxXUgpy7eFDLWh7VK4Q90nko9AsrWwwpv1fxYPEGJPQPcn9/i4ndv6+NT9TevLTSr", "n1004pv.res.private": "AAAAB3NzaC1yc2EAAAADAQABAAABAQDZNNQwnqOK16c0oWMyTl1teITBGCTn5SPYvXvhlBWety59KaoGKbkf4DA5k6 XTdfv4SiGVn8yzGfxgovsF0RfTM6m9da1IPGun6+QWijNRC/EX0fr2Gxx9ONktHk5tzXL7rucCJAOxKCdcHuGpKJW9NICesd6KhiDl+9Nlx463wZsgFY1K/N4PfNDI+nyYCQbAXdydbmRSoXLS5va4+Ktc7L4qnMif4h2nsk2vZp5b6CBCfJOqTmB58n2tI4gI8wkrEGfP2ol4CSMbQnHyu7V24EMvflGgSGGex uQtbuG9Cr8yenkCPZVytbUNq7uX6NGVazK+OPH2q5k5fPWJC4Ix", "n1005pv.res.private": "AAAAB3NzaC1yc2EAAAADAQABAAABAQCxwI58ww6pyPD/KobvGG520AliGsypwsrCY3XKtRPG5jxvhTEJucDGQr9BjOrC4dhqtr4fMt9mweHnElI+AzwvecwAs7XJ4/T/r8k7d4FDCQ57yGrbpP+7j2 aFGIBvETHbaij+zh29+orMzlyHdDA9etPuRzSPOaI91G9OCtNXUU8jlFhDPv1NJ2l0mykqztNSFJgDQqGqAuqj7WSWC+zrpOJTK8bTyx734Am/UEkhoBl+DFTV3DXb5H48vqGyL4HSgYgOqGKs+YunDfxTAy+PZ32Zwag82enPwkULABQPQ2Wr+rYTmRed0x2/31GWuzUSJSArGxTwiFfKMepH4yON"}, "msg" : "Could not connect to host(s): n1000pv.res.private, n1006pv.res.private, 10.236.209.24, n1002pv.res.private, 10.236.209.19."}

  266 2022-02-16 09:43:11,639 p=142158 u=viya n=ansible | ...ignoring

[...]

  328 2022-02-16 09:43:16,912 p=142158 u=viya n=ansible | TASK [Identify any pre-flight check failures] ******************************************************************************************************************************
  329 2022-02-16 09:43:16,976 p=142158 u=viya n=ansible | fatal: [deployTarget]: FAILED! => {"changed": false, "failed_when_result": true, "msg": "At least one pre-flight check failed on deployTarget: Could not connect to host(s): n1005pv.res.private, 10.236.209.24, n1004pv.res.private, 10.236.209.19."}
  330 2022-02-16 09:43:17,011 p=142158 u=viya n=ansible | fatal: [spre]: FAILED! => {"changed": false, "failed_when_result": true, "msg": "At least one pre-flight check failed on spre: Could not connect to host(s): n0999pv.res.private, 10.236.209.22, 10.236.209.21, 10.236.209.18."}
  331 2022-02-16 09:43:17,024 p=142158 u=viya n=ansible | fatal: [cas]: FAILED! => {"changed": false, "failed_when_result": true, "msg": "At least one pre-flight check failed on cas: Could not connect to host(s): n0999pv.res.private, 10.236.209.22, n1002pv.res.private."}
  332 2022-02-16 09:43:17,025 p=142158 u=viya n=ansible | fatal: [worker1]: FAILED! => {"changed": false, "failed_when_result": true, "msg": "At least one pre-flight check failed on worker1: Could not connect to host(s): n1000pv.res.private, n1006pv.res.private, 10.236.209.24, n1002pv.res.private, 10.236.209.19."}

Cheers

**Comment by erharb** [comment]
I don't think this can be considered a viya-ark specific issue, there's likely something misconfigured either in ansible or the environment being connected to. I'd recommend simplifying the inventory file and testing connections to it without using the viya-ark playbooks until ansible can successfully communicate with the host.

The ansible ping module is a good way to try out the inventory hosts are setup: https://docs.ansible.com/ansible/latest/user_guide/intro_getting_started.html#action-run-your-first-ansible-commands

**Comment by KaminoU** [comment]
Agreed with you, but as the choice is limited... I selected "bug" so my apologies for this tagging.

I also tried the ping part etc... That's why I am here.

Each command, tested manually works like a charm, but not together in a playbook.

I will check again about the Viya prerequesits...

Thank you

**Comment by erharb** [comment]
I would recommend reaching out to SAS Technical Support for assistance with getting these connections working since you'll need it to install SAS Viya itself as well.

**Comment by KaminoU** [comment]
Hello,

As the manual ssh-keyscan works like a charm... I just skipped the ssh-keyscan looping.

I still do believe that a sleep of few seconds in the ssh-keyscan looping could resolve this weird issue (especially that there is a random part in this issue - forgot to mention it)

Thanks in any case for your time =)
