### ISSUE TITLE
Playbook viya-services-status.yml does not check Apache httpd status and availability

### ISSUE THREAD

**Issue by JMPoilane** [sassoftware/viya-ark#90]
Dear all,

A customer experienced an issue where Viya 3.5 platform was down but viya-services-start.yml playbook showed that all was up and ok.
Indeed problem was due to Apache httpd service which entered in a failed state, therefore no interface could work. 

Could it be possible as future enhancement that httpd status would be tested (through some simple url check or other basic way) ?

Thanks in advance and sincerely.

Jean-Marie

**Comment by kevinlinglesas** [comment]
@JMPoilane, apologies for the long delay.  The viya-ark project has been in a mode of support/maintenance but not actively working on enhancements for some time now. Therefore, I am closing this issue.   Thank you for your submission.
