### ISSUE TITLE
pre.install fails to run with Ansible-Core 2.12.10 due to missing Ansible modules

### ISSUE THREAD

**Issue by miaeyg** [sassoftware/viya-ark#94]
**Describe the bug**

Unable to run the pre.install playbook when using Ansible-Core 2.12.10. Execution fails immediately:
ERROR! couldn't resolve module/action 'pam_limits'. This often indicates a misspelling, missing collection, or incorrect module path.

**Environment**
- [ ] Ansible version: 2.12.10
- [ ] Python version: 3.8
- [ ] OS version: RHEL 8 
- [ ] Failed playbook tasks log (or entire playbook log) [Attach]
- [ ] What version of Viya 3.x is being deployed? 3.5

**To Reproduce**
1. Install Ansible-Core 2.12.10 using "yum install"
2. Run the pre.install playbook

**Expected behavior**

**Comment by kevinlinglesas** [comment]
@miaeyg I believe I understand why you may have encountered this error.      If you have **only** ansible-core installed this error occurs.    

Viya ARK states ansible support based on the 'ansible-core' version.   After ansible 2.10, the project was restructured and the core was separated out from the 'ansible' module and the overall Ansible project versioning changed.   Ansible 4.0 (containing core 2.11),  Ansible 5.0 (containing core 2.12), etc.    

Viya ARK requires both 'ansible' and 'ansible-core'.    To achieve this you should install something like ansible==5.10.0 (as an example - the last release of 5.x project).

I reproduced your error when I did a 'pip uninstall ansible' and found that 'ansible --version' still returned the ansible-core information.   I had not realized this myself, but uninstalling 'ansible' doesn't remove 'ansible-core'.   With 'ansible' uninstalled and 'ansible-core' remaining, any exec of viya-ark pre-install playbook will result in the error you reported.

Please ensure the full ansible collection is installed (ie, ansible 5.x [core 2.12]).   Ex, pip install ansible==5.10.0
