### ISSUE TITLE
pre.install hangs in "verify sudo" step

### ISSUE THREAD

**Issue by miaeyg** [sassoftware/viya-ark#95]
**Describe the bug**

Running the pre.install playbook it hangs when it reaches the step where it verifies sudo access. The step executes the "sudo -l" command and prompts the user to enter his password and then hangs as the prompt is not visible to the user running the playbook. This does not make sense as the playbook was invoked with the "--ask-become-pass" option and the user was prompted for the password already.

**Environment**
- [ ] Ansible version: 2.9
- [ ] Python version: 3.8
- [ ] OS version:  RHEL 8
- [ ] Failed playbook tasks log (or entire playbook log) [Attach]
- [ ] What version of Viya 3.x is being deployed? 3.5

**To Reproduce**
1. Firstly, ...
2. Then, ...
3. 

**Expected behavior**

**Comment by miaeyg** [comment]
Hi @kevinlinglesas . The "--ask-become-pass" is required in this case as the user performing the installation has "sudo" permission but the "sudo" permission requires typing the password to allow the "sudo" command to work. The "--ask-become-pass" Ansible option addresses this specific case as it prompts for the password when invoking the ansible playbook.

**Comment by kevinlinglesas** [comment]
I have personally never used that option and will need to go take some time to understand and attempt to reproduce.    

Are you able to make progress with skip-tags?     

Frankly, it's been quite a while since digging into these playbooks so I will need to also re-familiarize a bit.

**Comment by miaeyg** [comment]
I managed to skip the “sudo” check so no problem with that
