### ISSUE TITLE
SAS Viya Deployment Report Playbook - Hot Fix report on environments with no Internet access

### ISSUE THREAD

**Issue by splmie** [sassoftware/viya-ark#97]
Regarding to SAS Viya Deployment Report Playbook. I would like to generate full report including hot fix section but unfortunately my Viya 3.5 environment has no access to Internet.
I know connectivity to sas.com is one of playbook's prerequisites but I'm wondering is there any workaround for Viya environments with no Internet access. I came up with these workarounds 

**Workaround #1 - dump sas.com content to offline file, use the offline file by playbook instead requesting sas.com directly**
1. On workstation with connectivity to sas.com somehow we will create file (kind offline database) by requesting sas.com as playbook does. The file includes all content needed by inventory playbook to generate hot fix report. 
2. The inventory file will be transferred by administrator to target Viya environment with no Internet access.
3. On target Viya environment in ansible command starting the playbook the downloaded file will be referenced as input file. 
4. Playbook will request input file instead of sas.com.

**Workaround #2 - generate yaml report without hot fix section, update base raport to full report on workstation with connectivity to sas.com**
1. Administrator generates SAS Viya Deployment Report on Viya 3.5 environment with no access to Internet. Report without Hot Fix section. 
2. Administrator transfers yaml report to workstation with connectivity to sas.com
3. Administrator runs SAS Viya Deployment Report playbook again referencing yaml file from first run as input file.
4. Playbook extends input report with hot fix section and in output generates full report.

**Comment by kevinlinglesas** [comment]
Thank you @splmie for your interest in SAS Viya Deployment Report and this enhancement request.   Unfortunately, we are not able to consider enhancement requests for this project due to available resources and other priorities of current contributors.
