### ISSUE TITLE
[Viya3.5] Pre-check by pre-install playbook

### ISSUE THREAD

**Issue by TakeshiMifune** [sassoftware/viya-ark#98]
In the pre-check by executing the pre-install playbook, python version check failed.
TASK [viya-ark.preinstall : Assert at least the minimum version of Python is used.] ********************************************************************************************
fatal: [deployTarget]: FAILED! => {
    "assertion": "ansible_python_version is version(required_python_min_version, '>=')",
    "changed": false,
    "evaluated_to": false,
    "msg": "It looks like you are using Python 3.6.8 but SAS deployment requires Python 3.10. The asserted minimum version of Python can be altered by changing 'required_python_min_version' in roles/viya-ark.preinstall/defaults/main.yml or bypass with '--skip-tags python_version_check'. See Python section of https://support.sas.com/en/documentation/third-party-software-reference/viya/35/support-for-operating-systems.html#ansible."
}

PLAY RECAP *********************************************************************************************************************************************************************
deployTarget               : ok=8    changed=0    unreachable=0    failed=1    skipped=1    rescued=0    ignored=0
localhost                  : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0

For python, refer to the following site and install it.
https://support.sas.com/en/documentation/third-party-software-reference/viya/35/support-for-operating-systems.html#ansible.

The confirmation results are as follows.
$ python3 --version
Python 3.11.2

$ sudo python3 -m pip list
Package      Version
------------ -------
ansible      7.7.0
ansible-core 2.14.7
bcrypt       4.0.1
cffi         1.15.1
cryptography 41.0.1
Jinja2       3.1.2
MarkupSafe   2.1.3
packaging    23.1
paramiko     3.2.0
pip          23.1.2
pycparser    2.21
PyNaCl       1.5.0
PyYAML       6.0
resolvelib   0.8.1
setuptools   68.0.0
wheel        0.40.0

I do not know the reason for the error and I am struggling to respond.
I would like to resolve the error, so could you please let me know if there are any missing settings or missing products that you can think of?

Best Regards,
Takeshi Mifune

**Comment by erharb** [comment]
@TakeshiMifune is your deployTarget host the same machine as local or a remote machine? Also on the deployTarget host can you please provide the information output by running `ansible-playbook --version`?

**Comment by TakeshiMifune** [comment]
Hello Eric,

Thank you for your response.

>is your deployTarget host the same machine as local or a remote machine?
deployTarget host is the same machine as local machine.

>ansible-playbook --version?
ansible-playbook [core 2.14.7]
  config file = None
  configured module search path = ['/home/scskuser/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.11/site-packages/ansible
  ansible collection location = /home/scskuser/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible-playbook
  python version = 3.11.2 (main, Jun  6 2023, 07:39:01) [GCC 8.5.0 20210514 (Red Hat 8.5.0-18)] (/bin/python3)
  jinja version = 3.1.2
  libyaml = True


Please let me know if you have any questions.

Best Regards,
Takeshi Mifune

**Comment by erharb** [comment]
The ansible python looks good, so my next thought is that whatever user which is being authenticated as to deployTarget could have PATH environment variable which is picking up the older version of python first. Can you try manually becoming that user and seeing which version of python3 is reported?

**Comment by TakeshiMifune** [comment]
Hello Eric,

Thank you for your help, I can close this issue.

Thanks and Regards,
Takeshi
