### ISSUE TITLE
How to restart two CAS controller with Viya-ark ?

### ISSUE THREAD

**Issue by nhousset** [sassoftware/viya-ark#99]
Hello,

We have an VIYA 3.5 environment 2two CAS controller (the first with 5 workers and the second with 3) and we would like to know if viya-ark supports this type of configuration. 
Today, we have two inventory.ini files, one initial with all the machine definitions and groups, and a second with the second controller case and workers (this is the file used when deploying the second CAS controller ).

What's the best way to stop/start/resart all the process via viya-ark in this type of configuration? 
Will it work to merge the two inventories, for stop/relaunch only? 
Or, should you still use a second inventory, but remove the httpproxy definition, for example, to avoid the stop/relaunch of the second case controller stopping the http proxy on the MS server? 

Thanks in advance for your suggestions. 

Nicolas Housset

**Comment by erharb** [comment]
The [viya-mmsu](https://github.com/sassoftware/viya-ark/tree/main/playbooks/viya-mmsu) tool only acts upon a single inventory.ini at a time, most likely it should work just fine on the separated inventory.ini. However, if you wish to create  custom merged inventory just for the purposes of managing the services with viya-mmsu (and customized to omit httpproxy) then that could be a good idea as well as long as you don't attempt to run deployment operations using that custom inventory.

**Comment by erharb** [comment]
Closing since there seems to be no further ask or activity.
